"""`adc_osc` -- the on-die ADC and oscillator of the 138C (`P3.T29`, `P3.T31`).

Two families that share a file because they share a question: the 25A model in
`chipdb.fse_create_adc`/`fse_create_osc` is built from 25A-only vendor tables
(`Adc25kIns`/`Adc25kOuts`, and an early return for `GW5AST-138C` in the
oscillator), and neither has ever been pointed at this die.  **The vendor is
asked before the model is written**: a `gw_sh` run says whether the die has the
block at all and, when it does, *where the vendor puts it* -- and that placement
is the anchor the `.dat` tables need, not something the tables can be made to
give up on their own (`P2.T08a` unlocked `AdcLRCIns`/`AdcLRCOuts`/`AdcULCOuts`
but their base has drifted, exactly as `Ae350SocIns`' did).

## ADC

The 138C's ADC primitives are `ADCLRC` and `ADCULC`, not the 25A's `ADC`
(`$GOWINHOME/IDE/simlib/gw5a/prim_sim.v:17539` and `:17592`, the latter
commented `//ADCULC,GW5AT-138K` in the vendor's own file).  Their analog
inputs are bank pads (`ADCINBK2A`.. on `ADCLRC`, `ADCINBK6A`.. on `ADCULC`),
which no fabric net can drive; the sweep therefore uses the **internal**
sources -- `VSENCTL` selects the on-die thermometer and the supply monitors --
so no analog ball is claimed and the board's IO envelope is untouched.

## OSC

`OSCA(OSCOUT, OSCEN)` with `FREQ_DIV`, per `cells_xtra_gw5a.v:1202`.  The shape
is `spec-primitives.md` §1's "one OSC driving a counter to an LED": the counter
is fabric, which is what makes the OSC row `E0` on `conns` by construction --
an oscillator has no pad to hang its consumer on, so `D105` cannot be honoured
here and the row says so instead of pretending.
"""
from ._io_base import IoShape

# --------------------------------------------------------------------------
# ADC
# --------------------------------------------------------------------------

#: `(primitive, VSENCTL, {parameter: value})` per sweep point, one axis per run.
#:
#: `VSENCTL` selects the measured source: 0 `adcv`, 1 `adct` (the on-die
#: thermometer), 2 `vdd09_0`, .. 7 `vdd33_1` (`prim_sim.v:17550`).  The two
#: primitives are the two corners the vendor's own `.dat` names -- `AdcLRC*`
#: for the lower-right corner block and `AdcULC*` for the upper-left one.
ADC_POINTS = {
    "adclrc-temp": ("ADCLRC", 1, {}),
    "adclrc-vdd09": ("ADCLRC", 2, {}),
    "adclrc-divctl2": ("ADCLRC", 1, {"DIV_CTL": "2'd2"}),
    "adculc-temp": ("ADCULC", 1, {}),
}

ADC_BASELINE = "adclrc-temp"

CLK_BALL = "V22"           # IOB104B, the board oscillator
DRSTN_BALL = "AB13"        # IOB89B, Key_in[0]
ADCEN_BALL = "T16"         # IOB76A, LCD_CTP[2]
ADCREQ_BALL = "T15"        # IOB70B, LCD_CTP[3]
RDY_BALL = "AA9"           # IOB53A, sk9822_da

#: One ball per bit for the low ten bits of the 14-bit result.
VALUE_BALLS = ("Y17", "W14", "Y14", "Y16", "AA16",
               "AB16", "AB17", "AA15", "W15", "W16")
#: The one ball the high four bits share, through a reduction LUT.
FOLD_BALL = "Y13"          # IOB87A, cmos_sda

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_ADC_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/adc_osc.py -- do not edit.
// Shape: adc (primitive under test: {primitive})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire clk,
    input  wire drstn,
    input  wire adcen,
    input  wire adcreq,
    output wire rdy,
    output wire fold,
{value_ports});

    wire [13:0] adcvalue;

    {primitive} dut (
        .VSENCTL      (3'd{vsenctl}),
        .FSCAL_VALUE  (10'd730),
        .OFFSET_VALUE (-12'sd1180),
        .ADCEN        (adcen),
        .CLK          (clk),
        .DRSTN        (drstn),
        .ADCREQI      (adcreq),
        .ADCRDY       (rdy),
        .ADCVALUE     (adcvalue)
    );
{defparams}
    assign {{q9, q8, q7, q6, q5, q4, q3, q2, q1, q0}} = adcvalue[9:0];
    // Bank 5 brings out eleven free balls, not fifteen: the high four bits
    // are reduced onto one.  See the module docstring.
    assign fold = ^adcvalue[13:10];

endmodule

`default_nettype wire
"""


class AdcShape(IoShape):
    """One on-die ADC per run, measuring an internal source."""

    name = "adc"
    primitive = "ADCLRC / ADCULC"
    sweep_axis = "POINT"
    sweep_values = list(ADC_POINTS)
    baseline_value = ADC_BASELINE
    ports = dict(
        {
            "clk": (CLK_BALL, "input"),
            "drstn": (DRSTN_BALL, "input", {"pull_mode": "UP"}),
            "adcen": (ADCEN_BALL, "input", {"pull_mode": "DOWN"}),
            "adcreq": (ADCREQ_BALL, "input", {"pull_mode": "DOWN"}),
            "rdy": (RDY_BALL, "output"),
        },
        **{"q%d" % i: (ball, "output")
           for i, ball in enumerate(VALUE_BALLS)},
        fold=(FOLD_BALL, "output"),
    )
    clocks = {"clk": 8.0}
    config_role_acks = {CLK_BALL: _ACK_CLK}
    #: The vendor's placement of the block is what this row measures, so the
    #: shape pins nothing and the comparison is not tile-scoped.
    scope_tiles = ()

    def rtl(self, sweep_value):
        primitive, vsenctl, params = ADC_POINTS[sweep_value]
        value_ports = "".join(
            "    output wire q%d%s\n"
            % (i, "," if i < len(VALUE_BALLS) - 1 else "")
            for i in range(len(VALUE_BALLS)))
        defparams = "".join("    defparam dut.%s = %s;\n" % kv
                            for kv in sorted(params.items()))
        return _ADC_TEMPLATE.format(
            primitive=primitive, axis=self.sweep_axis, point=sweep_value,
            top=self.top_module, vsenctl=vsenctl, value_ports=value_ports,
            defparams=defparams)


SPEC = AdcShape().spec()


# --------------------------------------------------------------------------
# OSC
# --------------------------------------------------------------------------

#: `FREQ_DIV` per sweep point.  `OSCA`'s own comment gives the legal set as
#: "3, 2~126 (only even num)" (`prim_sim.v:13220`), so `100` (the default),
#: `2` (the fastest), `126` (the slowest) and the odd exception `3` are the
#: four corners of the axis.  Only the first two are run here: this task's
#: oscillator budget is two vendor runs, and the row records that the other
#: two corners are unmeasured rather than implying the axis is closed.
#: `(primitive, FREQ_DIV)`.  `OSCB` is here because `OSCA` is the wrong
#: question on this die: the vendor answers `OSCA` with "There is no OSCA
#: resource in current device", and `cells_xtra_gw5a.v` declares a second
#: oscillator, `OSCB(OSCOUT, OSCREF, OSCEN, FMODE, RTRIM, RTCTRIM)`, whose
#: `OSCREF` output is documented as the reference for the SERDES and the PLL
#: (`prim_sim.v:13250`).  Whether *any* oscillator exists here is one more run.
OSC_POINTS = {
    "osca-div100": ("OSCA", 100),
    "osca-div2": ("OSCA", 2),
    "oscb-div10": ("OSCB", 10),
    "osca-div126": ("OSCA", 126),
    "osca-div3": ("OSCA", 3),
}

OSC_BASELINE = "osca-div100"

OSCEN_BALL = "AB13"        # IOB89B, Key_in[0]
LED_BALL = "AA9"           # IOB53A, sk9822_da
TAP_BALL = "Y17"           # IOB91A, HP_BCK -- the counter's low bit

#: The counter width.  Big enough that the vendor cannot fold the counter into
#: the oscillator's own cell and small enough to stay one CLS column.
OSC_COUNTER_BITS = 24

_OSC_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/adc_osc.py -- do not edit.
// Shape: osc (primitive under test: {axis})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire oscen,
    output wire led,
    output wire tap
);

    wire oscout;
    reg [{msb}:0] counter = 0;

{instance}

    always @(posedge oscout) counter <= counter + 1'b1;

    assign led = counter[{msb}];
    assign tap = counter[0];

endmodule

`default_nettype wire
"""


class OscShape(IoShape):
    """One on-die oscillator per run, driving a counter to two balls.

    Not `D105`-clean, and it cannot be: an `OSCA` has no pad, so its only
    consumer is fabric, and a freely placed counter gives the oscillator's net
    a different identity in each flow. The row is `E0` on `conns` by
    construction and says so rather than claiming an `E1` it cannot reach.
    """

    name = "osc"
    primitive = "OSCA / OSCB"
    sweep_axis = "FREQ_DIV"
    sweep_values = list(OSC_POINTS)
    baseline_value = OSC_BASELINE
    ports = {
        "oscen": (OSCEN_BALL, "input", {"pull_mode": "UP"}),
        "led": (LED_BALL, "output"),
        "tap": (TAP_BALL, "output"),
    }
    #: The oscillator is the clock; there is no clock ball to constrain.
    clocks = {}
    scope_tiles = ()

    def rtl(self, sweep_value):
        primitive, freq_div = OSC_POINTS[sweep_value]
        if primitive == "OSCA":
            instance = ("    OSCA dut (\n"
                        "        .OSCOUT (oscout),\n"
                        "        .OSCEN  (oscen)\n"
                        "    );\n")
        else:
            instance = ("    OSCB dut (\n"
                        "        .OSCOUT  (oscout),\n"
                        "        .OSCREF  (),\n"
                        "        .OSCEN   (oscen),\n"
                        "        .FMODE   (1'b0),\n"
                        "        .RTRIM   (8'h00),\n"
                        "        .RTCTRIM (6'h00)\n"
                        "    );\n")
        instance += "    defparam dut.FREQ_DIV = %d;\n" % freq_div
        return _OSC_TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            msb=OSC_COUNTER_BITS - 1, instance=instance)


