"""`clocking_pll_trace` -- one hard `PLL`, swept over the twelve 138C sites.

`P1.T19`. The primitive under test is a single hard `PLL` pinned by
`INS_LOC "dut_pll" PLL_<side>[<n>];`, and the **swept axis is the placement
itself**: one run per vendor site name. What each run measures is which grid
tiles the vendor's own placer puts the PLL's configuration fuses in, which is
what turns `P1.T17`'s twelve `.fse`-measured three-tile runs from *positions*
into *named sites with an anchor*.

Why a placement sweep rather than a parameter sweep: the 138C `.dat` names no
PLL site at all (`$OTC/evidence/plla/sites-138c.md` §4 -- all eight
`Pll{L,R}{T,B}{Ins,Outs}` tables are `0xffff`), so there is no table to read
the site names or the port wires out of. The only remaining oracle is the
vendor toolchain placing a PLL where we tell it to.

Site-name spelling, MEASURED, not assumed:

* `SUG1018-1.2E` "Arora V Design Physical Constraints User Guide" §2, note
  "PLL Constraint Location": `PLL_L[0]`, `PLL_L[1]`, ... / `PLL_R[0]`, ...,
  and the worked example `INS_LOC "pll_name" PLL_L[0];`
* `MUG1031E` (Tang Mega 138K Pro, this very die) uses the same literal form:
  `INS_LOC "u_Gowin_PLL_AE350/PLL_inst" PLL_R[0]` and
  `INS_LOC "u_Gowin_PLL_DDR3/PLL_inst" PLL_L[0]`
* `strings -a $GOWINHOME/IDE/bin/floorplanner` carries exactly
  `PLL_B[0..3]`, `PLL_L[0..3]`, `PLL_R[0..3]`, `PLL_T[0..1]`

The 4 L / 4 R / 4 B / 0 T shape of the sweep below is `P1.T17`'s independent
`.fse` measurement (twelve three-tile `shortval[35]` runs, four on each of the
left, right and bottom edges and none on top); the floorplanner's string table
is an IDE-wide list, not a per-device site list, so it corroborates the
spelling and the per-side index range but does not by itself fix the count.

Parameters are a single legal operating point, not a sweep: `FCLKIN` 50 MHz,
`IDIV_SEL` 1 -> PFD 50 MHz (DS1239E Table 3-18 `FPFDMIN` 19, `FPFDMAX` 81.25),
`FBDIV_SEL` 1, `MDIV_SEL` 16 -> FVCO 800 MHz (`FVCOMIN` 650, `FVCOMAX` 1300),
`ODIV0_SEL` 8 -> `CLKOUT0` 100 MHz (`FOUTMIN` 5.079, `FOUTMAX` 1000). Every
one of the five bounds is the `P1.T20` five-tuple, so a refusal here is a real
signal about the tuple and not about an arbitrary divider choice.

Pins are the four `smoke` already proved legal on this package (`P0.T19`):
ordinary I/O in banks 4 and 5, never 6 or 7 (`D20c`, `D54`), no `DRIVE` on an
input (`CT1108`).
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: The twelve vendor site names, in `P1.T17`'s side order (L, R, B).
SITES = (
    "PLL_L[0]", "PLL_L[1]", "PLL_L[2]", "PLL_L[3]",
    "PLL_R[0]", "PLL_R[1]", "PLL_R[2]", "PLL_R[3]",
    "PLL_B[0]", "PLL_B[1]", "PLL_B[2]", "PLL_B[3]",
)

#: `P1.T17` anchors: the lowest-column tile of each three-tile `shortval[35]`
#: run, as `(x, y)` = `(col, row)`.
ANCHOR_TILES = [
    (1, 27), (0, 45), (0, 63), (1, 81),
    (177, 27), (178, 45), (178, 63), (177, 81),
    (28, 108), (32, 108), (146, 108), (150, 108),
]

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire rst_n,
    input  wire din,
    output wire dout
);

    wire pll_clkout0;
    wire pll_lock;

    // The primitive under test. ONE hard PLL, placed by the INS_LOC line the
    // .cst carries for this sweep point.
    //
    // The cell type is `PLL`, not `PLLA`. MEASURED, oracle run
    // pll-trace-pilot-clocking_pll_trace-0000: a `PLLA` instantiation on this
    // part is refused outright with
    //     ERROR (RP0008) : There is no PLLA resource in current device,
    //                      please change device
    // which corroborates UG306-1.0.1E Table 5-11 ("PLLA Device Supported"
    // lists GW5A-25 and nothing else). `PLL` (prim_sim.v:13333) carries the
    // dynamic-divider ports FBDSEL/IDSEL/MDSEL/ODSELn/DTn/ENCLKn and has NO
    // MDIO/DRP ports -- exactly matching the 138C `.dat`, whose `PllIn` table
    // populates 131 of 216 rows while filling every MDCLK/MDOPC/MDAINC/MDWDI/
    // MDRDO row with -1.
    PLL #(
        .FCLKIN("50.0"),
        .IDIV_SEL(1),
        .FBDIV_SEL(1),
        .MDIV_SEL(16),
        .ODIV0_SEL(8),
        .CLKOUT0_EN("TRUE"),
        .CLKFB_SEL("INTERNAL")
    ) dut_pll (
        .CLKIN        (clk),
        .CLKFB        (1'b0),
        .RESET        (~rst_n),
        .PLLPWD       (1'b0),
        .RESET_I      (1'b0),
        .RESET_O      (1'b0),
        .FBDSEL       (6'b0),
        .IDSEL        (6'b0),
        .MDSEL        (7'b0),
        .MDSEL_FRAC   (3'b0),
        .ODSEL0       (7'b0), .ODSEL0_FRAC (3'b0),
        .ODSEL1       (7'b0), .ODSEL2 (7'b0), .ODSEL3 (7'b0),
        .ODSEL4       (7'b0), .ODSEL5 (7'b0), .ODSEL6 (7'b0),
        .DT0          (4'b0), .DT1 (4'b0), .DT2 (4'b0), .DT3 (4'b0),
        .ICPSEL       (6'b0),
        .LPFRES       (3'b0),
        .LPFCAP       (2'b0),
        .PSSEL        (3'b000),
        .PSDIR        (1'b0),
        .PSPULSE      (1'b0),
        .ENCLK0       (1'b1),
        .ENCLK1       (1'b0), .ENCLK2 (1'b0), .ENCLK3 (1'b0),
        .ENCLK4       (1'b0), .ENCLK5 (1'b0), .ENCLK6 (1'b0),
        .SSCPOL       (1'b0),
        .SSCON        (1'b0),
        .SSCMDSEL     (7'b0),
        .SSCMDSEL_FRAC(3'b0),
        .LOCK         (pll_lock),
        .CLKOUT0      (pll_clkout0),
        .CLKOUT1      (), .CLKOUT2 (), .CLKOUT3 (),
        .CLKOUT4      (), .CLKOUT5 (), .CLKOUT6 (),
        .CLKFBOUT     ()
    );

    // Context, NOT compared (F6): one flop in the PLL's own clock domain so
    // CLKOUT0 and LOCK are both really used and the placer cannot optimise
    // the PLL away.
    reg q;
    always @(posedge pll_clkout0)
        q <= din ^ pll_lock;

    assign dout = q;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    """Render this shape's Verilog for one sweep point."""
    return RTL.format(
        name=spec.name,
        primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value,
        top_module=spec.top_module,
    )


def site(sweep_value):
    """The `INS_LOC` site for one sweep point -- the sweep value *is* the site."""
    return SITES[0] if sweep_value is None else sweep_value


SPEC = ShapeSpec(
    name="clocking_pll_trace",
    primitive="PLL",
    sweep_axis="site",
    sweep_values=list(SITES),
    baseline_value=SITES[0],
    pins={
        "clk": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "rst_n": PinSpec(loc="AA10", bank=5, pull_mode="UP", drive=None, direction="input"),
        "din": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None, direction="input"),
        "dout": PinSpec(loc="P20", bank=4, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=ANCHOR_TILES),
    rtl=rtl,
    ins_loc={"dut_pll": site},
    clocks={"clk": 20.0},
)
