"""`clocking_clkdiv2` -- the CLKDIV2 sweep on the GW5AST-138C (`P1.T15`).

Two measured facts shape this file, both from `P1.T04`, and both departures
from the blueprint's assumptions:

1. **`CLKDIV2` takes no `DIV_MODE`.**  `prim_sim.v:13122` gives it exactly
   `(CLKOUT, HCLKIN, RESETN)`, and `gowin_pack.GW5A.get_CLKDIV2_fuses()`
   returns `[]` -- on this family the primitive has no attribute fuse of its
   own; its only bitstream effect is the `BK<sect>MUX<idx>_OUTSEL = DIV2`
   HCLK-mux setting (`gowin_pack.py:2565-2585`).  There is no "mode set" to
   sweep, so the swept axis is what the device actually varies: **which of the
   four lanes of an HCLK block the CLKDIV2 sits on**, and **how `RESETN` is
   driven**.
2. **`CLKDIV2.CLKOUT` cannot drive ordinary fabric** (vendor `CK2060`), so it
   chains into a `CLKDIV`, which clocks the counter -- the same structure as
   `examples/gw5a/clkdiv2_chain-tangmega138k.v`.  `nextpnr` places the pair
   together and the `CLKDIV2 -> CLKDIV` link is non-switchable
   (`gowin.cc:374-380`).

The lane axis is the point: `chipdb.py:1748-1757` gives a CLKDIV2 its
`HCLKIN` from **`HCLK_BUF_BO<blk><i>` as a fuseless node on even `i`** and
from the **`CLKDIV2_I<blk><i>` pip on odd `i`**, so the two input paths the
chipdb builder distinguishes are only both exercised by running both parities.
Lanes 0 and 2 cover the node path, lanes 1 and 3 the pip path.

Sweep, 7 points (`(lane, resetn)`):

    (0, "pin") (1, "pin") (2, "pin") (3, "pin")   both input paths, driven reset
    (0, "tied") (1, "tied") (2, "tied")           RESETN deasserted at 1'b1

`RESETN` tied to `1'b0` is **not** run: with the divider held in reset the
counter is constant and both synthesisers fold the whole design away, which
would be a measurement of the optimiser, not of the primitive.

Placement, as in `clocking_clkdiv`: the vendor by `INS_LOC "div0"
BOTTOMSIDE[4 + lane]` (block 5, `P1.T08d`), the open flow by the RTL
`(* BEL *)` attributes, because nextpnr's `.cst` reader cannot parse the
138C's `SIDE[0~7]` spelling.  This is the shape that needs `ShapeSpec.ins_loc`
to be a callable: the placement *is* the swept parameter.

The unpinned control is the sibling shape `clocking_clkdiv2_free`.
"""
from . import PinSpec, ScopeSpec, ShapeSpec
from .clocking_clkdiv import (BLOCK5_XY, DEFAULT_DIV_MODE, INS_LOC_INDEX,
                              _ACK_CLK, _ACK_RESET)

#: `(lane, resetn)`; lane parity selects the CLKDIV2 input path
#: (`chipdb.py:1748-1757`): even -> `HCLK_BUF_BO` node, odd -> `CLKDIV2_I` pip.
SWEEP = [(0, "pin"), (1, "pin"), (2, "pin"), (3, "pin"),
         (0, "tied"), (1, "tied"), (2, "tied")]
BASELINE = (0, "pin")

#: Which chipdb input path a lane index exercises -- recorded in the row's
#: `sweep` map so a reader never has to re-derive the parity rule.
INPUT_PATH = {0: "HCLK_BUF_BO", 1: "CLKDIV2_I", 2: "HCLK_BUF_BO", 3: "CLKDIV2_I"}

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = lane {lane} ({input_path}), RESETN {resetn}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire half_clk;
    wire div_clk;
    wire resetn = {resetn_expr};

    // The primitive under test.  CLKDIV2 takes no DIV_MODE (prim_sim.v:13122).
    (* BEL = "X{bx}Y{by}/CLKDIV2_{lane}" *) CLKDIV2 div2 (
        .HCLKIN (clk),
        .RESETN (resetn),
        .CLKOUT (half_clk)
    );

    // CLKDIV2.CLKOUT cannot drive fabric (CK2060), so it chains into a CLKDIV.
    (* BEL = "X{bx}Y{by}/CLKDIV_{lane}" *) CLKDIV div0 (
        .HCLKIN (half_clk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "{div_mode}";

    // Context, NOT compared: forces the divided clock out of the HCLK block.
    // A ring counter, deliberately NOT an adder: an adder packs into ALU
    // bels and the `c1` decode check unpacks the open bitstream with
    // `noalu=True`, so every ALU comes back missing (MEASURED, P1.T14 trial
    // run `p1t14-trial2`: 24 `c1_missing` ALU cells).  That is a gap in the
    // harness's ALU decode path, not a property of CLKDIV, and a shape whose
    // context is LUT+DFF only does not step on it.
    reg [3:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


def _point(sweep_value):
    lane, resetn = sweep_value if sweep_value is not None else BASELINE
    return int(lane), str(resetn)


def rtl(spec, sweep_value=None):
    lane, resetn = _point(sweep_value)
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis, top_module=spec.top_module,
        bx=BLOCK5_XY[0], by=BLOCK5_XY[1], lane=lane, resetn=resetn,
        input_path=INPUT_PATH[lane], div_mode=DEFAULT_DIV_MODE,
        resetn_expr="reset" if resetn == "pin" else "1'b1")


def ins_loc(spec, sweep_value=None):
    """The vendor pin for this sweep point: block 5, the swept lane."""
    lane, _ = _point(sweep_value)
    return {"div0": "BOTTOMSIDE[%d]" % (INS_LOC_INDEX + lane)}


SPEC = ShapeSpec(
    name="clocking_clkdiv2",
    primitive="CLKDIV2",
    sweep_axis="lane_resetn",
    sweep_values=SWEEP,
    baseline_value=BASELINE,
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[list(BLOCK5_XY)]),
    rtl=rtl,
    ins_loc=ins_loc,
    clocks={"clk": 20.0},
)
