"""`clocking_clkdiv_free` -- the unpinned CLKDIV control run (`P1.T14`).

Byte-for-byte the `clocking_clkdiv` design at the documented default
`DIV_MODE = "2"`, with **both** placement pins removed: no `INS_LOC` for the
vendor and no `(* BEL *)` for the open flow.  It is the control the pinned
sweep is read against -- it says what the two placers do when neither is told
anything, and it is therefore an `E0` row by construction (`P1.T08d` measured
`cells=4 attrs=8 conns=0` for exactly this free case, the block-4-versus-5
placement difference).

A separate shape file rather than a sweep point of `clocking_clkdiv` because
the comparison **level** is a property of the batch, not of the sweep point:
`python -m fuzz.gw5ast138c.harness` takes one `--level` for the whole batch.
"""
from . import PinSpec, ScopeSpec, ShapeSpec
from .clocking_clkdiv import (BLOCK5_XY, DEFAULT_DIV_MODE, _ACK_CLK,
                              _ACK_RESET)

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}  (placement free on BOTH flows)
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire div_clk;

    CLKDIV div0 (
        .HCLKIN (clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "{div_mode}";

    // A ring counter, deliberately NOT an adder: an adder packs into ALU
    // bels and the `c1` decode check unpacks the open bitstream with
    // `noalu=True`, so every ALU comes back missing (MEASURED, P1.T14 trial
    // run `p1t14-trial2`: 24 `c1_missing` ALU cells).  That is a gap in the
    // harness's ALU decode path, not a property of CLKDIV, and a shape whose
    // context is LUT+DFF only does not step on it.
    reg [3:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value if sweep_value is not None else spec.baseline_value,
        top_module=spec.top_module, div_mode=DEFAULT_DIV_MODE)


SPEC = ShapeSpec(
    name="clocking_clkdiv_free",
    primitive="CLKDIV",
    sweep_axis="placement",
    sweep_values=["free"],
    baseline_value="free",
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[list(BLOCK5_XY)]),
    rtl=rtl,
    ins_loc={},
    clocks={"clk": 20.0},
)
