"""`clocking_dhce` -- the DHCE gate, one design per (HCLK block, lane).

`P1.T27`'s row.  One `DHCE` gating the clock of one `CLKDIV`, the divider
pinned to a named lane on both sides, swept over six `(block, lane)` points in
the two bottom HCLK blocks.  What the sweep proves is the thing `P1.T26`'s
allocation-order sweep could not separate: a DHCE **site index is the lane
index**, so the fuse a lone DHCE sets is the enable of input multiplexer
`lane`, in that block's cell and nowhere else.

Four points: the four lanes of block 5.  Blocks 0 and 1 have no modelled
clock escape (`D100a`), and the side blocks reach the central clock mux over
the same lane wires the bottom pair do -- a side point would re-measure the
escape map, not the gate.  The cross-block half is measured on the **vendor**
side only (`evidence/dhcen/gate_probe.py`, block 4 lanes 0 and 2) rather than
swept here, because a `ShapeSpec` carries one static tile scope: adding block
4 to it would put the `CEN` net's long-wire hops *through* the other block
inside the compared scope, where they are a routing difference of a net whose
endpoint set the vendor does not have, and the row would measure that instead
of the gate.

The `DHCE` carries no `BEL` attribute: nextpnr binds a `$PACKER_DHCEN_*`
placeholder to every hardware site and marks the one whose lane wire the
gated clock is routed over (`globals.cc route_dhcen_net`), erasing the design
cell before placement -- so the site is chosen by the route, exactly as the
vendor chooses it, and a `BEL` here would assert a placement the flow does not
use.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: `(block cell (row, col), Himbaechel site (x, y), lane, INS_LOC site)`.
#: The `INS_LOC` -> (block, lane) map is `P1.T08d`'s
#: (`$OTC/evidence/hclk/mux38-138c.md` 2).
POINTS = {
    "b5l0": ((108, 117), (117, 108), 0, "BOTTOMSIDE[4]"),
    "b5l1": ((108, 117), (117, 108), 1, "BOTTOMSIDE[5]"),
    "b5l2": ((108, 117), (117, 108), 2, "BOTTOMSIDE[6]"),
    "b5l3": ((108, 117), (117, 108), 3, "BOTTOMSIDE[7]"),
}

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    input  wire cen,
    output wire [3:0] led
);

    wire gated_clk;
    wire div_clk;

    // The gate.  Its whole bitstream signature is the output-enable bit of
    // the HCLK input multiplexer of the lane its clock lands on (P1.T26 for
    // the bit, P1.T27 for the lane).
    DHCE gate0 (
        .CLKIN  (clk),
        .CEN    (cen),
        .CLKOUT (gated_clk)
    );

    // Lane {lane} of block cell {block}.  The vendor is pinned by
    // INS_LOC "div0" {site} in top.cst.
    (* BEL = "X{bx}Y{by}/CLKDIV_{lane}" *) CLKDIV div0 (
        .HCLKIN (gated_clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "4";

    // Context, NOT compared (the scope is the two HCLK block cells): the
    // counter is what forces the divided clock out of the block and onto the
    // global clock network.  A ring counter, deliberately not an adder: the
    // `c1` decode check unpacks with `noalu=True` (MEASURED, P1.T14).
    reg [3:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    block, (bx, by), lane, site = POINTS[value]
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis, sweep_value=value,
        top_module=spec.top_module,
        block=block, bx=bx, by=by, lane=lane, site=site)


def ins_loc(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    return {"div0": POINTS[value][3]}


#: The MEASURED evidence each config-role exemption rests on (`P1.T14`).
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_dhce",
    primitive="DHCE",
    sweep_axis="site",
    sweep_values=list(POINTS),
    baseline_value="b5l0",
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "cen": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None,
                       direction="input"),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[[117, 108]]),
    rtl=rtl,
    ins_loc=ins_loc,
    clocks={"clk": 20.0},
)
