"""`clocking_e2e` -- Phase 1's end-to-end clock tree, one design, one run.

The phase's own end-to-end proof (`P1-clocking.md` §E2E): **one** design that
carries a whole clock path -- board clock -> HCLK spine -> two `CLKDIV`s on
two different lanes of one HCLK block, at two different `DIV_MODE`s -> the
global clock network -> fabric -> LEDs -- built twice, once by the vendor
oracle and once by the open flow, and compared at `E1` with placement
identity.  It is distinct from the per-row sweeps: each of those isolates one
primitive on one lane, this one asserts that the six-block model, the lane
mapping and the divider fuses still agree when two lanes of the same block are
configured differently in the same bitstream.

**What the design does not contain, and why -- all MEASURED, none chosen.**

* No `PLL`.  `P1.T23` closed the PLL row on the vendor side and recorded four
  gaps that stop the *open* half at the packer, one of them hard:
  `GW5AST_138C.get_pll_pump()` is unimplemented and its constants need their
  own campaign (`$OTC/evidence/plla/openflow-gap-138c.md`).  A PLL here would
  make the run `ABORT` in `gowin_pack` and measure that gap instead of the
  clock tree.  The board clock drives the spine directly, over the same HCLK
  lanes.
* No `CLKDIV2`.  `CLKDIV2.CLKOUT` cannot drive ordinary fabric (vendor
  `CK2060`, `P1.T04`) and the primitive writes no fuse of its own (`P1.T15`,
  `D103`), so adding it would put an inferred cell on the critical path of a
  comparison whose point is decoded identity.  `P1.T15` owns that row.
* No `DHCE`.  MEASURED here, on this shape's own first run
  (`p1t38b-e2e-clocking_e2e-0000`, `$OTC/evidence/clocking/e2e-138c.md`): the
  open flow never sets the gate.  `globals.cc get_dhcen_bel` matches a routed
  wire against the `dhcen` pip apicula records, which for block 5 lane 0 is
  `HCLK_UNK1003 -> HCLK_UNK999`; the vendor's own bitstream for the same
  design instead sets `HCLK_UNK999 = "HCLK_UNK1007"`, a different source, and
  the open route into the block never touches that wire at all, so
  `DHCEN_USED` is never set and `get_DHCEN_fuses` returns nothing.  That is
  `P1.T27`'s row to close, not something this design can work around.
* No `DQCE`/`DCS`.  `P1.T28` derived their 138C tile types from vendor runs;
  neither has an open-flow bel on this device yet, so a `DCS` here would fail
  in nextpnr for a reason that has nothing to do with the clock tree.

Placement is pinned on both sides, which is what makes `E1` mean anything:
the vendor by `INS_LOC "div0" BOTTOMSIDE[4]` / `"div2" BOTTOMSIDE[6]`
(SUG1018-1.7E §2.9, block 5 lanes 0 and 2 -- `P1.T08d`), the open flow by the
RTL `BEL` attributes, because nextpnr's `.cst` reader cannot parse the 138C's
`SIDE[0~7]` spelling (`P1.T14`).  Blocks 0 and 1 are avoided: no modelled
clock escape (`D100a`).
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: HCLK block 5 of the 138C: `chipdb._gw5a_hclk_locs['GW5AST-138C'][5]` is
#: `(row 108, col 117)`, so the Himbaechel site is `X117Y108` (`P1.T04`).
BLOCK5_XY = (117, 108)

#: `INS_LOC` index -> the block/lane the `BEL` attributes name (`P1.T08d`:
#: `BOTTOMSIDE[4..7]` is block 5, lanes 0..3).
INS_LOC_BASE = 4
LANE_A, LANE_B = 0, 2

#: Two modes, deliberately neither the `"2"` default (`gowin_pack.py:5645`):
#: a run that lost a `defparam` shows up as a different one-hot fuse rather
#: than as silence.
DIV_MODE_A, DIV_MODE_B = "4", "8"

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire div_clk_a;
    wire div_clk_b;

    // Lane {lane_a} of block 5.  The vendor is pinned by
    // INS_LOC "div0" BOTTOMSIDE[{ins_a}] in top.cst.
    (* BEL = "X{bx}Y{by}/CLKDIV_{lane_a}" *) CLKDIV div0 (
        .HCLKIN (clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk_a)
    );
    defparam div0.DIV_MODE = "{div_a}";

    // Lane {lane_b} of the SAME block, at a different mode: the point of the
    // design is that two lanes configured differently coexist in one
    // bitstream and both decode.
    (* BEL = "X{bx}Y{by}/CLKDIV_{lane_b}" *) CLKDIV div2 (
        .HCLKIN (clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk_b)
    );
    defparam div2.DIV_MODE = "{div_b}";

    // Context, NOT compared (the E0 scope is the HCLK block cell only): the
    // counters are what force each divided clock out of the block and onto
    // the global clock network.  Ring counters, deliberately not adders: the
    // `c1` decode check unpacks with `noalu=True`, so an ALU comes back
    // missing for a reason that is not the clock tree (MEASURED, P1.T14).
    reg [1:0] ring_a;
    always @(posedge div_clk_a)
        ring_a <= {{ring_a[0], ~ring_a[1]}};

    reg [1:0] ring_b;
    always @(posedge div_clk_b)
        ring_b <= {{ring_b[0], ~ring_b[1]}};

    assign led = {{ring_b, ring_a}};

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value if sweep_value is not None else spec.baseline_value,
        top_module=spec.top_module,
        bx=BLOCK5_XY[0], by=BLOCK5_XY[1],
        lane_a=LANE_A, lane_b=LANE_B,
        div_a=DIV_MODE_A, div_b=DIV_MODE_B,
        ins_a=INS_LOC_BASE + LANE_A)


#: The MEASURED evidence each config-role exemption rests on (`P1.T14`).
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_e2e",
    primitive="HCLK block",
    sweep_axis="design",
    sweep_values=["two-lane-clkdiv"],
    baseline_value="two-lane-clkdiv",
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[list(BLOCK5_XY)]),
    rtl=rtl,
    ins_loc={"div0": "BOTTOMSIDE[%d]" % (INS_LOC_BASE + LANE_A),
             "div2": "BOTTOMSIDE[%d]" % (INS_LOC_BASE + LANE_B)},
    clocks={"clk": 20.0},
)
