"""`clocking_pll_attrmap` -- one hard `PLL` at one site, one parameter varied per run.

`P1.T22`. Where `clocking_pll_trace` (`P1.T19`) held the parameters fixed and
swept the *placement*, this shape does the opposite: the `PLL` is pinned to
`PLL_L[0]` for every run and exactly **one** primitive parameter differs from
the baseline. The measurement is therefore a pure attribute->fuse attribution:
whatever bits move between the baseline `.fs` and a sweep point's `.fs`, inside
the three tiles of that site, are the fuses of the one attribute that changed.

Site, MEASURED (`P1.T19`): `INS_LOC "dut_pll" PLL_L[0]` lands on the three-tile
`shortval[35]` group at row 27, columns 1, 2, 3 (ttyps 74, 75, 76) --
`$OTC/evidence/plla/sites-138c.json`, `pll_idx` 0.

Operating point, MEASURED against the `P1.T20` five-tuple
`(FINMAX 800, FOUTMAX 1000, FOUTMIN 5.079, FVCOMAX 1300, FVCOMIN 650)` and
against DS1239E Table 3-18's `FPFDMIN 19` / `FPFDMAX 81.25`:

    FCLKIN 100 MHz, IDIV_SEL 2, FBDIV_SEL 2, MDIV_SEL 13, ODIV0_SEL 8
    Fpfd   = FCLKIN / IDIV        = 50      MHz   (19 .. 81.25)
    Fclkfb = Fpfd  * FBDIV        = 100     MHz
    FVCO   = Fclkfb * MDIV        = 1300    MHz   (650 .. 1300)
    CLKOUT0= FVCO  / ODIV0        = 162.5   MHz   (5.079 .. 1000)

The baseline deliberately sits at `FVCOMAX`, because the VCO band is only a
factor of two wide: a baseline in the middle of it would make *every* single
integer divider step illegal in one direction. From `FVCO = 1300` the legal
one-parameter moves are `IDIV` up (1300 -> 866.67 -> 650), `FBDIV` down
(-> 650) and `MDIV` down (-> 1000, 700); `ODIV0` does not touch the VCO at all.

Every point below therefore differs from `p00_baseline` in exactly one
`#(...)` parameter; the port list is byte-identical across all twelve, so a
fuse that moves cannot be a connectivity artefact.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: `INS_LOC` site, fixed for every run of this shape.
SITE = "PLL_L[0]"

#: The three tiles of `PLL_L[0]` as `(x, y)` = `(col, row)`
#: (`sites-138c.json`, `pll_idx` 0: row 27, cols 1-3).
SCOPE_TILES = [(1, 27), (2, 27), (3, 27)]

#: The baseline parameter set. Keys are `PLL` parameter names exactly as
#: `prim_syns/gw5a/primitive.xml` spells them.
BASELINE = {
    "FCLKIN": '"100.0"',
    "IDIV_SEL": "2",
    "FBDIV_SEL": "2",
    "MDIV_SEL": "13",
    "ODIV0_SEL": "8",
    "ODIV1_SEL": "8",
    "CLKOUT0_EN": '"TRUE"',
    "CLKOUT1_EN": '"FALSE"',
    "CLKFB_SEL": '"INTERNAL"',
    "DYN_IDIV_SEL": '"FALSE"',
    "DYN_ODIV0_SEL": '"FALSE"',
}

#: `name -> (parameter, value)`: the ONE parameter this point changes.
#: `p00_baseline` changes nothing and is the reference `.fs`.
POINTS = {
    "p00_baseline":    (None, None),
    "p01_idiv3":       ("IDIV_SEL", "3"),          # FVCO 866.67
    "p02_idiv4":       ("IDIV_SEL", "4"),          # FVCO 650
    "p03_fbdiv1":      ("FBDIV_SEL", "1"),         # FVCO 650
    "p04_mdiv7":       ("MDIV_SEL", "7"),          # FVCO 700
    "p05_mdiv10":      ("MDIV_SEL", "10"),         # FVCO 1000
    "p06_odiv0_4":     ("ODIV0_SEL", "4"),         # CLKOUT0 325
    "p07_odiv0_16":    ("ODIV0_SEL", "16"),        # CLKOUT0 81.25
    "p08_odiv0_64":    ("ODIV0_SEL", "64"),        # CLKOUT0 20.3125
    "p09_dyn_idiv":    ("DYN_IDIV_SEL", '"TRUE"'),
    "p10_dyn_odiv0":   ("DYN_ODIV0_SEL", '"TRUE"'),
    "p11_clkout1_en":  ("CLKOUT1_EN", '"TRUE"'),
}

#: Parameter emission order, so the generated Verilog is byte-stable.
PARAM_ORDER = list(BASELINE)

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}  ({changed})
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire rst_n,
    input  wire din,
    output wire dout
);

    wire pll_clkout0;
    wire pll_lock;

    // The primitive under test. The cell type is `PLL`, not `PLLA` (`D96`).
    // Only the #(...) block varies between the twelve points of this shape;
    // the port list below is identical in every one of them.
    PLL #(
{params}
    ) dut_pll (
        .CLKIN        (clk),
        .CLKFB        (1'b0),
        .RESET        (~rst_n),
        .PLLPWD       (1'b0),
        .RESET_I      (1'b0),
        .RESET_O      (1'b0),
        .FBDSEL       (6'b0),
        .IDSEL        (6'b0),
        .MDSEL        (7'b0),
        .MDSEL_FRAC   (3'b0),
        .ODSEL0       (7'b0), .ODSEL0_FRAC (3'b0),
        .ODSEL1       (7'b0), .ODSEL2 (7'b0), .ODSEL3 (7'b0),
        .ODSEL4       (7'b0), .ODSEL5 (7'b0), .ODSEL6 (7'b0),
        .DT0          (4'b0), .DT1 (4'b0), .DT2 (4'b0), .DT3 (4'b0),
        .ICPSEL       (6'b0),
        .LPFRES       (3'b0),
        .LPFCAP       (2'b0),
        .PSSEL        (3'b000),
        .PSDIR        (1'b0),
        .PSPULSE      (1'b0),
        .ENCLK0       (1'b1),
        .ENCLK1       (1'b0), .ENCLK2 (1'b0), .ENCLK3 (1'b0),
        .ENCLK4       (1'b0), .ENCLK5 (1'b0), .ENCLK6 (1'b0),
        .SSCPOL       (1'b0),
        .SSCON        (1'b0),
        .SSCMDSEL     (7'b0),
        .SSCMDSEL_FRAC(3'b0),
        .LOCK         (pll_lock),
        .CLKOUT0      (pll_clkout0),
        .CLKOUT1      (), .CLKOUT2 (), .CLKOUT3 (),
        .CLKOUT4      (), .CLKOUT5 (), .CLKOUT6 (),
        .CLKFBOUT     ()
    );

    // Context, NOT compared (F6): one flop in the PLL's own clock domain so
    // CLKOUT0 and LOCK are both really used and the placer cannot optimise
    // the PLL away.
    reg q;
    always @(posedge pll_clkout0)
        q <= din ^ pll_lock;

    assign dout = q;

endmodule

`default_nettype wire
"""


def params_for(sweep_value):
    """The full parameter dict for one sweep point (baseline + the one change)."""
    if sweep_value is None:
        sweep_value = "p00_baseline"
    if sweep_value not in POINTS:
        raise ValueError(f"{sweep_value!r} is not a point of clocking_pll_attrmap")
    parms = dict(BASELINE)
    attr, val = POINTS[sweep_value]
    if attr is not None:
        parms[attr] = val
    return parms


def rtl(spec, sweep_value=None):
    """Render this shape's Verilog for one sweep point."""
    point = sweep_value or "p00_baseline"
    parms = params_for(point)
    attr, val = POINTS[point]
    changed = "baseline" if attr is None else f"{attr} = {val}"
    lines = [f"        .{a}({parms[a]})" for a in PARAM_ORDER]
    return RTL.format(
        name=spec.name,
        primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=point,
        changed=changed,
        params=",\n".join(lines),
        top_module=spec.top_module,
    )


def site(sweep_value):
    """The `INS_LOC` site -- fixed for every point of this shape."""
    return SITE


SPEC = ShapeSpec(
    name="clocking_pll_attrmap",
    primitive="PLL",
    sweep_axis="pll_param",
    sweep_values=list(POINTS),
    baseline_value="p00_baseline",
    pins={
        "clk": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "rst_n": PinSpec(loc="AA10", bank=5, pull_mode="UP", drive=None, direction="input"),
        "din": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None, direction="input"),
        "dout": PinSpec(loc="P20", bank=4, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=SCOPE_TILES),
    rtl=rtl,
    ins_loc={"dut_pll": site},
    clocks={"clk": 10.0},
)
