"""`clocking_pll_bottom` -- a bottom-edge `PLL` clocking fabric (`P1.F3`, gap b).

`P1.T40` recorded that from `PLL_B[2]` nextpnr could not route `MPLLCLKOUT0`
to a fabric flop at all, while `PLL_L[0]` could, and left the asymmetry as a
named gap.

`p1f3-pll-route/b-b0`..`b-b3` say what the asymmetry is: a bottom-edge site
has no clock-plane wire of its own.  The vendor takes its output to fabric and
back in through a logic-to-clock **gate**, and the gate drives the quadrant
spine directly -- `(81, 85) SPINE9 <= BRMDCLK1` in `b-b0` and `b-b1`.  The
database dropped every such row, because a non-bridge cell's spine was only
allowed a `CBRIDGEOUT*` source (`$OTC/evidence/plla/hclk-entry-138c.md`).

The compared scope is the site's own three tiles: the ring counter is context,
and its placement is not pinned on either side.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: `PLL_B[0]`: anchor tile (row 108, col 28), three tiles wide.
PLL_TILES = [[28, 108], [29, 108], [30, 108]]

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire pll_clkout0;
    wire pll_lock;

    // The P1.T39 reference operating point: FCLKIN 50 MHz, IDIV 1, FBDIV 1,
    // MDIV 16, ODIV0 8 -> FVCO 800 MHz, CLKOUT0 100 MHz.
    PLL #(
        .FCLKIN("50.0"), .IDIV_SEL(1), .FBDIV_SEL(1),
        .MDIV_SEL(16), .ODIV0_SEL(8)
    ) dut_pll (
        .CLKIN(clk), .CLKFB(1'b0), .RESET(~reset), .PLLPWD(1'b0),
        .RESET_I(1'b0), .RESET_O(1'b0),
        .FBDSEL(6'b0), .IDSEL(6'b0), .MDSEL(7'b0), .MDSEL_FRAC(3'b0),
        .ODSEL0(7'b0), .ODSEL0_FRAC(3'b0),
        .ODSEL1(7'b0), .ODSEL2(7'b0), .ODSEL3(7'b0),
        .ODSEL4(7'b0), .ODSEL5(7'b0), .ODSEL6(7'b0),
        .DT0(4'b0), .DT1(4'b0), .DT2(4'b0), .DT3(4'b0),
        .ICPSEL(6'b0), .LPFRES(3'b0), .LPFCAP(2'b0),
        .PSSEL(3'b000), .PSDIR(1'b0), .PSPULSE(1'b0),
        .ENCLK0(1'b1), .ENCLK1(1'b0), .ENCLK2(1'b0), .ENCLK3(1'b0),
        .ENCLK4(1'b0), .ENCLK5(1'b0), .ENCLK6(1'b0),
        .SSCPOL(1'b0), .SSCON(1'b0), .SSCMDSEL(7'b0), .SSCMDSEL_FRAC(3'b0),
        .LOCK(pll_lock), .CLKOUT0(pll_clkout0),
        .CLKOUT1(), .CLKOUT2(), .CLKOUT3(), .CLKOUT4(), .CLKOUT5(),
        .CLKOUT6(), .CLKFBOUT()
    );

    // The one thing the gap said was impossible: a fabric flop on the output
    // of a bottom-edge site.  A ring counter, not an adder: the `c1` decode
    // check unpacks with `noalu=True` (MEASURED, P1.T14).
    reg [2:0] ring;
    always @(posedge pll_clkout0)
        ring <= {{ring[1:0], ~ring[2]}};

    assign led = {{pll_lock, ring}};

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis, sweep_value=value,
        top_module=spec.top_module)


#: The MEASURED evidence each config-role exemption rests on (`P1.T14`).
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_pll_bottom",
    primitive="PLL",
    sweep_axis="site",
    sweep_values=["b0"],
    baseline_value="b0",
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=PLL_TILES),
    rtl=rtl,
    ins_loc={"dut_pll": "PLL_B[0]"},
    clocks={"clk": 20.0},
)
