"""`clocking_dhcen_trace` -- the DHCEN control-pin tracing shape (`P1.T25`).

The primitive apicula calls **DHCEN** is spelled **`DHCE`** on the GW5A family
and its enable port is **`CEN`**, not `CE`.  That is measured, not assumed:

* `GowinIDE 1.9.12.03/IDE/ipcore/DHCEN/dhcen.ipspec` lists supported devices for
  the GW1* and GW2* families only -- **no `GW5*` line at all**;
* a `DHCEN` instantiation on `GW5AST-138C` is refused by GowinSynthesis with
  ``ERROR (EX3937) : Instantiating unknown module 'DHCEN'``;
* the family primitive table `IDE/bin/prim_syns/gw5a/primitive.xml` carries
  ``<name>DHCE</name>`` with ports ``CLKIN``, ``CEN``, ``CLKOUT`` (and `DCE`
  with ``CE`` where the older families have `DQCE`);
* a `DHCE` instantiation compiles, places and routes, and the vendor's own
  ``Clock Resource Usage Summary`` then prints a ``DHCE  n/24`` line, which is
  where the device's DHCEN capacity is read from.

Method (the maintainer's own, `apycula/chipdb.py` `_dhcen_ce` comment): build
vendor images with the maximum allowable number of DHCE instances whose enable
ports are driven from IO, then trace the route from the IO to the final wire --
that wire is the enable port of the DHCEN bel.  Each `DHCE` feeds one `CLKDIV`
so that the vendor is forced to allocate a distinct HCLK input multiplexer per
instance; all enables share **one** IO net, so a single package pin suffices
for 24 instances and the whole enable fan-out is one connected component of the
routing graph, which is exactly the set the trace wants.

The sweep axis is the DHCE instance count.  `0` is the baseline (the same
`CLKDIV` chain with no `DHCE` in front of it), so the presence diff attributes
fuses and pips to the DHCE instances alone; `25` is the deliberate
over-subscription that makes the vendor state the capacity as a refusal.

This shape is **measurement-only**: it has no `E0`/`E1` verdict, because there
is no open-source side to compare against until `P1.T26` teaches
`fse_create_dhcen` about the device.  `scope` therefore names the six measured
HCLK block cells of `evidence/clocking/hclk-topology.md` (`P1.T04`), which is
where the enable wires are expected to land.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: The six measured HCLK block cells of the GW5AST-138C (`P1.T04`), as
#: `(row, col)` in apicula's 0-based grid.  The DHCEN enable wires are looked
#: for in these cells.
HCLK_CELLS = [(27, 0), (27, 181), (81, 0), (81, 181), (108, 64), (108, 117)]

#: Vendor-stated DHCE capacity of the GW5AST-138C, from the
#: `Clock Resource Usage Summary` of any successful run (`DHCE n/24`).
DHCE_CAPACITY = 24

HEADER = """\
// Generated by fuzz.gw5ast138c.shapes.clocking_dhcen_trace -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none
"""


def rtl(spec, sweep_value=None, tie_resetn=False, n_div=None):
    """Render the Verilog for one sweep point.

    `sweep_value` is the number of `DHCE` instances.  Each drives the
    `HCLKIN` of its own `CLKDIV`; at `sweep_value == 0` the `CLKDIV` chain is
    driven straight from the clock pin, which is the presence-diff baseline.

    `tie_resetn` is the **disambiguation** variant, and it is what makes the
    trace unambiguous.  With `RESETN` driven from the `rst_n` pin there are
    *two* IO-driven nets ending inside the HCLK block cells -- the enables and
    the `CLKDIV` resets -- and both have exactly one end per instance, so a
    structural trace cannot tell them apart.  Tying `RESETN` to a constant
    leaves the enable net as the only IO-driven net that reaches the blocks;
    the `rst_n` pin is kept (and xor-ed into the output) so the `.cst` and the
    package pin-out are unchanged between the two variants.

    `n_div` overrides the `CLKDIV` count, which defaults to the `DHCE` count.
    The control point of the campaign is `sweep_value=0, n_div=24`: the full
    complement of `CLKDIV` with **no** `DHCE` in front of them.  It separates
    the enable net from the `CLKDIV` `CALIB` net, which is the other net that
    ends once per instance inside every HCLK block cell.
    """
    n = 0 if sweep_value is None else int(sweep_value)
    n_div = max(n, 1) if n_div is None else int(n_div)
    lines = [HEADER.format(name=spec.name, primitive=spec.primitive,
                           sweep_axis=spec.sweep_axis, sweep_value=n),
             "module {} (".format(spec.top_module),
             "    input  wire clk,",
             "    input  wire rst_n,",
             "    input  wire cen,",
             "    output wire dout",
             ");",
             "    wire [{}:0] hclk;".format(n_div - 1),
             "    wire [{}:0] div;".format(n_div - 1)]
    for i in range(n_div):
        resetn = "1'b1" if tie_resetn else "rst_n"
        if i < n:
            lines.append("    DHCE dh{0} (.CLKOUT(hclk[{0}]), .CLKIN(clk), "
                         ".CEN(cen));".format(i))
        else:
            lines.append("    assign hclk[{0}] = clk;".format(i))
        lines.append("    CLKDIV cd{0} (.CLKOUT(div[{0}]), .CALIB(1'b0), "
                     ".HCLKIN(hclk[{0}]), .RESETN({1}));".format(i, resetn))
        lines.append('    defparam cd{0}.DIV_MODE = "2";'.format(i))
    tail = " ^ rst_n" if tie_resetn else ""
    lines += ["    assign dout = ^div{};".format(tail), "endmodule",
              "`default_nettype wire"]
    return "\n".join(lines) + "\n"


SPEC = ShapeSpec(
    name="clocking_dhcen_trace",
    primitive="DHCE",
    sweep_axis="n_dhce",
    sweep_values=[0, 1, 2, 3, 4, 5, 6, 8, 12, 16, 20, 24, 25],
    baseline_value=0,
    pins={
        "clk": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "rst_n": PinSpec(loc="AA10", bank=5, pull_mode="UP", drive=None,
                         direction="input"),
        "cen": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None,
                       direction="input"),
        "dout": PinSpec(loc="P20", bank=4, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[(col, row) for row, col in HCLK_CELLS]),
    rtl=rtl,
    clocks={"clk": 20.0},
)
