"""`clocking_pll_pump` -- the GW5AST-138C charge-pump characterisation shape.

`P1.T41`.  Sibling of `clocking_pll`, deliberately a **separate** shape rather
than another axis of it: `clocking_pll` sweeps one parameter against an axis
baseline so a moved fuse attributes to that parameter, whereas this shape moves
`FCLKIN`, `IDIV`, `FBDIV` and `MDIV` together on purpose, to place the PLL at a
chosen `(fref, fvco)` and read the charge-pump attributes the vendor *derived*
there.  Mixing the two in one file would break `clocking_pll`'s
"exactly one parameter differs from its axis baseline" invariant.

What it measures, and why it has to be measured
-----------------------------------------------
`GW5A.get_pll_attrvals` (`gowin_pack.py`) derives four attributes from
`get_pll_pump(fref, fvco)` alone -- `FLDCOUNT` (16), `KVCO` (28),
`A_ICP_SEL` (111) and `A_LPF_RES_SEL` (112) -- and `get_pll_pump` needs
`get_pll_freq_R` and `get_pll_coeffs`, which exist only on `GW5A_25A`.  Those
are loop-filter constants with no datasheet source and they cannot be borrowed
from the 25A: that part's VCO band is `[800, 1600]` MHz against this one's
`[650, 1300]`, so its curve is a different curve.  Each point below is one
vendor `.fs` from which the four attributes are read back out of the site's
`shortval[35]` table, and the set of points is the fit's design matrix.

The design matrix
-----------------
`DS1239E` Table 3-18 pins `Fpfd` to `[19, 81.25]` MHz and `FVCO` to
`[650, 1300]` MHz, so `Ndiv = FVCO / fref` can only run over `[8, 68.4]` and
the reachable `(fref, Ndiv)` region is a wedge, not a rectangle.  The ten
points below are its corners and edges: both `Ndiv` extremes at each of six
`fref` values spanning the whole legal `Fpfd` band.  `P1.T23`'s batch A adds
twenty more points for free (`fref` 22.2 .. 44.4, `Ndiv` 26 .. 46) and
`P1.T41`'s batch B seven more (`fref` 25, `Ndiv` 26 .. 52); this shape buys
only what those cannot reach.

Every point is realised exactly, with no rounding: `fref = FCLKIN / IDIV` and
`Ndiv = FBDIV * MDIV` are both integers-in, so `FVCO = fref * Ndiv` is the
arithmetic the vendor itself does.
"""
from . import PinSpec, ScopeSpec, ShapeSpec
from .clocking_pll import BASE_PARAMS, DEFAULT_SITE, PARAM_ORDER, scope_tiles

#: `(name, FCLKIN, IDIV, FBDIV, MDIV)`.  `fref = FCLKIN/IDIV`,
#: `Ndiv = FBDIV*MDIV`, `FVCO = fref*Ndiv`, `CLKOUT0 = FVCO/8`.
#:
#: `FBDIV_SEL` is odd at every point that uses it as the whole of `Ndiv`
#: (`attrmap-138c.md` §4 observed `A_FBDIV_SEL` over `1..63` odd); everywhere
#: else `FBDIV` is `1` and `MDIV` carries `Ndiv`, which the `.fse` names over
#: `1..127`.
POINTS = (
    # fref 19 MHz -- the FPFDMIN corner, both Ndiv extremes.
    ("f19_n35",   76.0,  4, 35,  1),   # FVCO  665
    ("f19_n68",   76.0,  4,  1, 68),   # FVCO 1292
    # fref 20 MHz, mid Ndiv.
    ("f20_n50",   80.0,  4,  1, 50),   # FVCO 1000
    # fref 40 MHz.
    ("f40_n17",  400.0, 10, 17,  1),   # FVCO  680
    ("f40_n32",  400.0, 10,  1, 32),   # FVCO 1280
    # fref 50 MHz.
    ("f50_n13",  400.0,  8, 13,  1),   # FVCO  650
    ("f50_n26",  400.0,  8,  1, 26),   # FVCO 1300
    # fref 65 MHz.
    ("f65_n10",  650.0, 10,  1, 10),   # FVCO  650
    ("f65_n20",  650.0, 10,  1, 20),   # FVCO 1300
    # fref 81.25 MHz -- the FPFDMAX corner.
    ("f81_n16",  650.0,  8,  1, 16),   # FVCO 1300
)

POINT_BY_NAME = {p[0]: p for p in POINTS}

#: `CLKOUT0` divider, constant across the shape: `FVCO/8` is inside
#: `[5.079, 1000]` MHz at every point, so `ODIV0` never has to move and can
#: never be confused with a pump effect.
ODIV0 = 8


def operating_point(name):
    """`(fclkin, idiv, fbdiv, mdiv)` of one point."""
    _, fclkin, idiv, fbdiv, mdiv = POINT_BY_NAME[name]
    return fclkin, idiv, fbdiv, mdiv


def fref(name):
    fclkin, idiv, _fbdiv, _mdiv = operating_point(name)
    return fclkin / idiv


def ndiv(name):
    _fclkin, _idiv, fbdiv, mdiv = operating_point(name)
    return fbdiv * mdiv


def fvco(name):
    return fref(name) * ndiv(name)


def clkout0(name):
    return fvco(name) / ODIV0


def params(name):
    """The `#(...)` block of one point."""
    fclkin, idiv, fbdiv, mdiv = operating_point(name)
    parms = dict(BASE_PARAMS)
    parms.update({
        "FCLKIN": f'"{fclkin:.1f}"',
        "IDIV_SEL": str(idiv),
        "FBDIV_SEL": str(fbdiv),
        "MDIV_SEL": str(mdiv),
        "ODIV0_SEL": str(ODIV0),
    })
    return parms


def sweep_record(name):
    """The evidence `sweep` map of one point -- the whole operating point."""
    fclkin, idiv, fbdiv, mdiv = operating_point(name)
    return {"axis": "PUMP", "point": name, "FCLKIN": fclkin,
            "IDIV_SEL": idiv, "FBDIV_SEL": fbdiv, "MDIV_SEL": mdiv}


RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Pump point {point}: fref {fref:.6f} MHz, Ndiv {ndiv}, FVCO {fvco:.6f} MHz,
// CLKOUT0 {clkout0:.6f} MHz
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire rst_n,
    input  wire din,
    output wire dout
);

    wire pll_clkout0;
    wire pll_lock;

    // The primitive under test. The cell type is `PLL`, not `PLLA` (`D96`).
    // The port list is byte-identical to `clocking_pll`'s, so a bit that moves
    // between the two shapes is a parameter effect and never a connectivity
    // artefact.
    PLL #(
{params}
    ) dut_pll (
        .CLKIN        (clk),
        .CLKFB        (1'b0),
        .RESET        (~rst_n),
        .PLLPWD       (1'b0),
        .RESET_I      (1'b0),
        .RESET_O      (1'b0),
        .FBDSEL       (6'b0),
        .IDSEL        (6'b0),
        .MDSEL        (7'b0),
        .MDSEL_FRAC   (3'b0),
        .ODSEL0       (7'b0), .ODSEL0_FRAC (3'b0),
        .ODSEL1       (7'b0), .ODSEL2 (7'b0), .ODSEL3 (7'b0),
        .ODSEL4       (7'b0), .ODSEL5 (7'b0), .ODSEL6 (7'b0),
        .DT0          (4'b0), .DT1 (4'b0), .DT2 (4'b0), .DT3 (4'b0),
        .ICPSEL       (6'b0),
        .LPFRES       (3'b0),
        .LPFCAP       (2'b0),
        .PSSEL        (3'b000),
        .PSDIR        (1'b0),
        .PSPULSE      (1'b0),
        .ENCLK0       (1'b1),
        .ENCLK1       (1'b0), .ENCLK2 (1'b0), .ENCLK3 (1'b0),
        .ENCLK4       (1'b0), .ENCLK5 (1'b0), .ENCLK6 (1'b0),
        .SSCPOL       (1'b0),
        .SSCON        (1'b0),
        .SSCMDSEL     (7'b0),
        .SSCMDSEL_FRAC(3'b0),
        .LOCK         (pll_lock),
        .CLKOUT0      (pll_clkout0),
        .CLKOUT1      (), .CLKOUT2 (), .CLKOUT3 (),
        .CLKOUT4      (), .CLKOUT5 (), .CLKOUT6 (),
        .CLKFBOUT     ()
    );

    // Context, NOT compared (F6): one fabric flop in the PLL's own clock
    // domain, so CLKOUT0 really has to reach the clock network and neither
    // CLKOUT0 nor LOCK can be optimised away.
    reg q;
    always @(posedge pll_clkout0)
        q <= din ^ pll_lock;

    assign dout = q;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    """Render this shape's Verilog for one pump point."""
    point = sweep_value or SPEC.baseline_value
    parms = params(point)
    lines = [f"        .{a}({parms[a]})" for a in PARAM_ORDER]
    return RTL.format(
        name=spec.name,
        primitive=spec.primitive,
        point=point,
        fref=fref(point),
        ndiv=ndiv(point),
        fvco=fvco(point),
        clkout0=clkout0(point),
        params=",\n".join(lines),
        top_module=spec.top_module,
    )


def site(sweep_value):
    """Every point sits at the site `P1.T22`/`P1.T23` attributed (`E1`)."""
    return DEFAULT_SITE


SPEC = ShapeSpec(
    name="clocking_pll_pump",
    primitive="PLL",
    sweep_axis="pump_point",
    sweep_values=[p[0] for p in POINTS],
    baseline_value=POINTS[0][0],
    pins={
        "clk": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "rst_n": PinSpec(loc="AA10", bank=5, pull_mode="UP", drive=None, direction="input"),
        "din": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None, direction="input"),
        "dout": PinSpec(loc="P20", bank=4, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=scope_tiles(DEFAULT_SITE)),
    rtl=rtl,
    ins_loc={"dut_pll": site},
    # The fastest FCLKIN of the matrix (650 MHz); the SDC constrains the input
    # pin only and no point's fuses depend on it.
    clocks={"clk": 1.538},
)
