"""`clocking_dcs` -- the GW5AST-138C glitch-free clock mux (`DCS`).

`P1.T31`/`P1.T32`.  `n` simultaneous `DCS` instances, each driving its own
clock net, swept until the vendor refuses -- the capacity is what says how
many quadrants this die really carries, which is the question `S9` asks and
which `chipdb.py`'s pre-5A quadrant allow-list only guesses at.

All four `CLKIN` of an instance are driven from the same package clock.  Only
four I/O locations on this part are measured good (`P0.T19`), so four
independent clock pins are not available; a `DCS` is a black box to synthesis,
so it still programs all four of its input multiplexers, which is the thing
being attributed.  `CLKSEL` and `SELFORCE` come from a shift register clocked
by that same pin, so the selection is dynamic and the vendor cannot fold the
mux away.
"""
import os

from .clocking_dqce import CST, SDC  # same four measured bank-4/5 locations

#: `UG306-1.0.1E` S3.2.  `RISING` is the vendor's own default and the one
#: `examples/gw5a/dcs.v` uses.
DCS_MODES = ("RISING", "FALLING", "CLK0_GND", "CLK0_VCC")


def rtl(n_dcs, mode="RISING"):
    """`top.v` with `n_dcs` `DCS` instances, each on its own clock net."""
    assert n_dcs >= 1
    L = ["`default_nettype none",
         "module top (input wire clk, input wire rst_n, input wire key,",
         "            output wire dout);",
         f"    reg  [{4 * n_dcs - 1}:0] sel;",
         f"    reg  [{n_dcs - 1}:0] force_n;",
         f"    wire [{n_dcs - 1}:0] muxed;",
         f"    reg  [{n_dcs - 1}:0] q;",
         "    always @(posedge clk) sel <= {sel[%d:0], key};" % (4 * n_dcs - 2),
         "    always @(posedge clk) force_n <= {force_n[%d:0], rst_n};"
         % (n_dcs - 2) if n_dcs > 1 else
         "    always @(posedge clk) force_n <= rst_n;",
         "    genvar gi;",
         "    generate",
         f"        for (gi = 0; gi < {n_dcs}; gi = gi + 1) begin : g",
         "            DCS dcs (",
         "                .CLKOUT   (muxed[gi]),",
         "                .CLKIN0   (clk),",
         "                .CLKIN1   (clk),",
         "                .CLKIN2   (clk),",
         "                .CLKIN3   (clk),",
         "                .CLKSEL   (sel[gi * 4 +: 4]),",
         "                .SELFORCE (force_n[gi])",
         "            );",
         f'            defparam dcs.DCS_MODE = "{mode}";',
         "            always @(posedge muxed[gi]) q[gi] <= ~q[gi] ^ rst_n;",
         "        end",
         "    endgenerate",
         "    assign dout = ^q;",
         "endmodule",
         "`default_nettype wire"]
    return "\n".join(L) + "\n"


def write_design(d, n_dcs, mode="RISING"):
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "top.v"), "w").write(rtl(n_dcs, mode))
    open(os.path.join(d, "top.cst"), "w").write(CST)
    open(os.path.join(d, "top.sdc"), "w").write(SDC)


# ---------------------------------------------------------------- the E1 row

#: MEASURED (`P1.T31`, batch `p1t31-dcs`): the die's four DCS sit two in each
#: of the two clock-bridge cells that carry a spine multiplexer -- cell
#: (54, 93) carries `P26A-D`/`P27A-D` (spines 14 and 15), cell (54, 88)
#: carries `P36A-D`/`P37A-D` (spines 22 and 23).  A design with one `DCS`
#: lands on `P26*` in (54, 93) every time.
POINTS = {
    "q1": ((54, 93), "SPINE14"),
    "q2": ((54, 88), "SPINE22"),
}

#: A sweep point whose four `CLKIN` carry four **different** clocks, so
#: `CLKSEL` selects among distinct sources instead of among four copies of
#: one.  It is the design the DCS input side exists for: `P1.F2` added it once
#: the input multiplexers had a driver at all (`evidence/dcs/input-side-138c.md`).
#: Only one clock-capable location is measured good on this part, so the other
#: three clocks are fabric-divided from it.
SEL_POINT = "sel4"

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; the same 27 P1.T08d runs used it as "
              "reset")

E1_RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    input  wire cen,
    output wire [3:0] led
);

    wire muxed_clk;

    // The selection is dynamic so the mux cannot be folded away.  All four
    // CLKIN come from the one package clock: this part has one measured
    // clock-capable location, and a DCS is a black box to synthesis, so it
    // still programs all four of its input multiplexers -- which is the thing
    // being compared.
    reg [3:0] sel;
    always @(posedge clk)
        sel <= {{sel[2:0], cen}};

    DCS dcs0 (
        .CLKOUT   (muxed_clk),
        .CLKIN0   (clk),
        .CLKIN1   (clk),
        .CLKIN2   (clk),
        .CLKIN3   (clk),
        .CLKSEL   (sel),
        .SELFORCE (reset)
    );
    defparam dcs0.DCS_MODE = "{mode}";

    // Context, NOT compared: a ring counter, deliberately not an adder, so the
    // `c1` decode check unpacks with noalu=True (MEASURED, P1.T14).
    reg [3:0] ring;
    always @(posedge muxed_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


#: The `sel4` point's body, spliced into `E1_RTL` in place of the four
#: identical `CLKIN`.  The divider chain is deliberately a chain: three
#: independent clock nets the vendor cannot fold into one.
SEL4_DIVIDERS = """\
    reg d1 = 1'b0, d2 = 1'b0, d3 = 1'b0;
    always @(posedge clk) d1 <= ~d1;
    always @(posedge d1)  d2 <= ~d2;
    always @(posedge d2)  d3 <= ~d3;
"""

SEL4_CLKIN = """\
        .CLKIN0   (clk),
        .CLKIN1   (d1),
        .CLKIN2   (d2),
        .CLKIN3   (d3),"""

_UNIFORM_COMMENT = """\
    // The selection is dynamic so the mux cannot be folded away.  All four
    // CLKIN come from the one package clock: this part has one measured
    // clock-capable location, and a DCS is a black box to synthesis, so it
    // still programs all four of its input multiplexers -- which is the thing
    // being compared."""

SEL4_COMMENT = """\
    // The selection is dynamic so the mux cannot be folded away, and the four
    // CLKIN carry four different clocks, so it selects among distinct sources.
    // Only one clock-capable location is measured good on this part, so the
    // other three are fabric-divided from it."""

_UNIFORM_CLKIN = """\
        .CLKIN0   (clk),
        .CLKIN1   (clk),
        .CLKIN2   (clk),
        .CLKIN3   (clk),"""


def e1_rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    rtl = E1_RTL.format(
        name=spec.name, primitive=spec.primitive, sweep_axis=spec.sweep_axis,
        sweep_value=value, top_module=spec.top_module, mode="RISING")
    if value == SEL_POINT:
        rtl = rtl.replace(_UNIFORM_CLKIN, SEL4_CLKIN)
        rtl = rtl.replace(_UNIFORM_COMMENT, SEL4_COMMENT)
        rtl = rtl.replace("    reg [3:0] sel;",
                          SEL4_DIVIDERS + "\n    reg [3:0] sel;")
    return rtl


def _spec():
    from . import PinSpec, ScopeSpec, ShapeSpec
    return ShapeSpec(
        name="clocking_dcs",
        primitive="DCS",
        sweep_axis="quadrant",
        sweep_values=list(POINTS) + [SEL_POINT],
        baseline_value="q1",
        pins={
            "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                           config_role_ack=_ACK_CLK),
            "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                             direction="input", config_role_ack=_ACK_RESET),
            "cen": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None,
                           direction="input"),
            "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
            "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
            "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
            "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
        },
        bank_vccio={4: "3.3", 5: "3.3"},
        # Both clock-bridge cells: which of the two quadrants hosts the
        # DQCE is the router's choice, not the design's, so a scope of
        # one of them would compare an empty tile whenever the two
        # flows chose differently.
        scope=ScopeSpec(tiles=[[93, 54], [88, 54]]),
        rtl=e1_rtl,
        clocks={"clk": 20.0},
    )


SPEC = _spec()
