"""`clocking_four_globals` -- four independent global clocks (`P1.F3`, gap c).

`P1.T40` recorded that four independent global clock nets break nextpnr.  They
do, and not for a capacity reason: MEASURED on the design below, the **first**
buffered net is already refused --

    Warning: Failed to route net 'clk3_IBUF_I_O' from X91Y99/CLK1
             to X76Y107/CLK0 using dedicated routing.
    ERROR: Can't route the clk3_IBUF_I_O net.

with every spine still free.  A `BUFG` sits on one logic-to-clock gate and a
gate drives only part of the clock plane, so with four buffers the placer --
which has no cost term for that -- is bound to put at least one of them on a
gate that cannot reach its loads (`$OTC/evidence/clocking/four-globals-138c.md`).

Four clocks, four buffered global nets -- and one `CLKDIV`, pinned on both
sides, so the comparison has a fuse-backed scope while the design still
carries the four buffered nets that are the defect.  MEASURED: this design is
refused on the pre-fix pair and builds on the fixed one.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: HCLK block 5 (row 108, col 117); `INS_LOC` `BOTTOMSIDE[4..7]` are its
#: lanes 0..3 (`P1.T08d`, `$OTC/evidence/hclk/mux38-138c.md` 2).
BLOCK5_XY = [117, 108]
INS_LOC_BASE = 4

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk0,
    input  wire clk1,
    input  wire clk2,
    input  wire clk3,
    input  wire reset,
    output wire [3:0] led
);

    wire div_clk;

    // The fuse-backed part of the design: lane 0 of block 5, pinned on both
    // sides (INS_LOC "div0" BOTTOMSIDE[4] in top.cst).
    (* BEL = "X117Y108/CLKDIV_0" *) CLKDIV div0 (
        .HCLKIN (clk0),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "4";

    // Context, NOT compared (the scope is the block cell): one flop per raw
    // clock, which is what makes each of the four a buffered global net that
    // has to reach ordinary fabric.  Ring counters, deliberately not adders:
    // the `c1` decode check unpacks with `noalu=True` (MEASURED, P1.T14).
    reg d0;
    reg [3:0] raw;
    always @(posedge div_clk) d0 <= ~d0;
    always @(posedge clk0) raw[0] <= ~raw[0];
    always @(posedge clk1) raw[1] <= ~raw[1];
    always @(posedge clk2) raw[2] <= ~raw[2];
    always @(posedge clk3) raw[3] <= ~raw[3];

    assign led = raw ^ {{3'b0, d0}};

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis, sweep_value=value,
        top_module=spec.top_module)


#: The MEASURED evidence each config-role exemption rests on (`P1.T14`).
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_four_globals",
    primitive="HCLK block",
    sweep_axis="site",
    sweep_values=["b5"],
    baseline_value="b5",
    pins={
        "clk0": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                        config_role_ack=_ACK_CLK),
        "clk1": PinSpec(loc="Y12", bank=5, drive=None, direction="input",
                        config_role_ack=_ACK_RESET),
        "clk2": PinSpec(loc="AA11", bank=5, drive=None, direction="input"),
        "clk3": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "reset": PinSpec(loc="AA10", bank=5, pull_mode="UP", drive=None,
                         direction="input"),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[BLOCK5_XY]),
    rtl=rtl,
    ins_loc={"div0": "BOTTOMSIDE[4]"},
    clocks={"clk0": 20.0, "clk1": 20.0, "clk2": 20.0, "clk3": 20.0},
)
