"""`clocking_pll_hclk` -- a hard `PLL` clocking an HCLK lane (`P1.F3`, gap a).

`P1.T40` recorded that the open flow could not build this at all: nextpnr
refused `MPLLCLKOUT0 -> CLKDIV_I50` "using dedicated routing", and the E2E
design had to run its `PLL` beside the HCLK chain instead of through it.

The vendor does build it, and `p1f3-pll-route/a-l0-hclk` says how: the site's
`CLKOUT0` is the clock-plane wire `TLPLL0CLK0`, the bridge cell programs
`SPINE9 <= TLPLL0CLK0`, and the lane is entered from the block cell's own
`CLK0` off a global branch (`L2HCLK50`).  Every hop is a global one; what the
database was missing was only the wire at the site's end
(`$OTC/evidence/plla/hclk-entry-138c.md`).

One point: the site whose clock wire is measured.  A site with no measured
clock wire reaches the plane through a logic-to-clock gate instead and is the
`clocking_pll_bottom` row, not this one.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: `PLL_L[0]`: anchor tile (row 27, col 1), three tiles wide.
PLL_TILES = [[1, 27], [2, 27], [3, 27]]

#: HCLK block 5 (`chipdb._gw5a_hclk_locs['GW5AST-138C'][5]` = row 108,
#: col 117) and lane 0 -- `INS_LOC "div0" BOTTOMSIDE[4]` (`P1.T08d`).
BLOCK5_XY = [117, 108]

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire pll_clkout0;
    wire pll_lock;
    wire div_clk;

    // The P1.T39 reference operating point: FCLKIN 50 MHz, IDIV 1, FBDIV 1,
    // MDIV 16, ODIV0 8 -> FVCO 800 MHz, CLKOUT0 100 MHz.
    PLL #(
        .FCLKIN("50.0"), .IDIV_SEL(1), .FBDIV_SEL(1),
        .MDIV_SEL(16), .ODIV0_SEL(8)
    ) dut_pll (
        .CLKIN(clk), .CLKFB(1'b0), .RESET(~reset), .PLLPWD(1'b0),
        .RESET_I(1'b0), .RESET_O(1'b0),
        .FBDSEL(6'b0), .IDSEL(6'b0), .MDSEL(7'b0), .MDSEL_FRAC(3'b0),
        .ODSEL0(7'b0), .ODSEL0_FRAC(3'b0),
        .ODSEL1(7'b0), .ODSEL2(7'b0), .ODSEL3(7'b0),
        .ODSEL4(7'b0), .ODSEL5(7'b0), .ODSEL6(7'b0),
        .DT0(4'b0), .DT1(4'b0), .DT2(4'b0), .DT3(4'b0),
        .ICPSEL(6'b0), .LPFRES(3'b0), .LPFCAP(2'b0),
        .PSSEL(3'b000), .PSDIR(1'b0), .PSPULSE(1'b0),
        .ENCLK0(1'b1), .ENCLK1(1'b0), .ENCLK2(1'b0), .ENCLK3(1'b0),
        .ENCLK4(1'b0), .ENCLK5(1'b0), .ENCLK6(1'b0),
        .SSCPOL(1'b0), .SSCON(1'b0), .SSCMDSEL(7'b0), .SSCMDSEL_FRAC(3'b0),
        .LOCK(pll_lock), .CLKOUT0(pll_clkout0),
        .CLKOUT1(), .CLKOUT2(), .CLKOUT3(), .CLKOUT4(), .CLKOUT5(),
        .CLKOUT6(), .CLKFBOUT()
    );

    // The cascade the phase asked for and could not build: the PLL output is
    // the HCLK lane's clock.
    (* BEL = "X117Y108/CLKDIV_0" *) CLKDIV div0 (
        .HCLKIN (pll_clkout0),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "4";

    // Context, NOT compared: the ring counter is what forces the divided
    // clock onto the global network.  A ring counter, not an adder: the `c1`
    // decode check unpacks with `noalu=True` (MEASURED, P1.T14).
    reg [2:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[1:0], ~ring[2]}};

    assign led = {{pll_lock, ring}};

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis, sweep_value=value,
        top_module=spec.top_module)


#: The MEASURED evidence each config-role exemption rests on (`P1.T14`).
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_pll_hclk",
    primitive="PLL",
    sweep_axis="site",
    sweep_values=["l0_b5l0"],
    baseline_value="l0_b5l0",
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=PLL_TILES + [BLOCK5_XY]),
    rtl=rtl,
    ins_loc={"dut_pll": "PLL_L[0]", "div0": "BOTTOMSIDE[4]"},
    clocks={"clk": 20.0},
)
