"""`clocking_dqce` -- the GW5AST-138C dynamic clock enable (vendor name `DCE`).

`P1.T29`/`P1.T30`.  `P1.T28` established the four grid tile types the pre-5A
builder searches for and measured three of them live; what it could not settle
was how many `DCE` the die really hosts and which spines they gate.  This shape
answers that by capacity: `n` simultaneous `DCE` instances, each with its own
`CLKOUT` net (so each needs its own spine) and its own enable net, swept until
the vendor refuses.

The primitive is spelled `DCE` on this family, not `DQCE` -- GowinSynthesis
answers `ERROR (EX3937) : Instantiating unknown module 'DQCE'`, and
`UG306-1.0.1E` calls it `DCE`.  apycula's internal `extra_func['dqce']` key is
an apycula convention and keeps its spelling.
"""
import os

#: The four measured bank-4/5 locations (`P0.T19`/`P0.T20`), reused verbatim
#: from `shapes/clocking_dqce_probe.py` so the two campaigns share a pinout.
CST = """IO_LOC  "clk" AA9;
IO_PORT "clk" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "rst_n" AA10;
IO_PORT "rst_n" IO_TYPE=LVCMOS33 PULL_MODE=UP PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "key" AA11;
IO_PORT "key" IO_TYPE=LVCMOS33 PULL_MODE=UP PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "dout" P20;
IO_PORT "dout" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
"""
SDC = "create_clock -name clk -period 20 -waveform {0 10} [get_ports {clk}]\n"


def rtl(n_dce):
    """`top.v` with `n_dce` `DCE` instances, each on its own clock net.

    The enables come from a shift register clocked by `clk` rather than from
    combinational functions of the two spare pins: `n` distinct enable nets are
    needed to keep the vendor from merging instances, and only four pins are
    known good on this part.
    """
    assert n_dce >= 1
    L = ["`default_nettype none",
         "module top (input wire clk, input wire rst_n, input wire key,",
         "            output wire dout);",
         f"    reg  [{n_dce - 1}:0] ce;",
         f"    wire [{n_dce - 1}:0] gated;",
         f"    reg  [{n_dce - 1}:0] q;",
         "    always @(posedge clk) ce <= {ce[%d:0], key};" % (n_dce - 2)
         if n_dce > 1 else "    always @(posedge clk) ce <= key;",
         "    genvar gi;",
         "    generate",
         f"        for (gi = 0; gi < {n_dce}; gi = gi + 1) begin : g",
         "            DCE dce (.CLKIN(clk), .CE(ce[gi]), .CLKOUT(gated[gi]));",
         "            always @(posedge gated[gi]) q[gi] <= ~q[gi] ^ rst_n;",
         "        end",
         "    endgenerate",
         "    assign dout = ^q;",
         "endmodule",
         "`default_nettype wire"]
    return "\n".join(L) + "\n"


def write_design(d, n_dce):
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, "top.v"), "w").write(rtl(n_dce))
    open(os.path.join(d, "top.cst"), "w").write(CST)
    open(os.path.join(d, "top.sdc"), "w").write(SDC)


# ---------------------------------------------------------------- the E1 row

#: MEASURED (`P1.T29`, batch `p1t29-dce`): the die's twelve DQCE sit six in
#: each of the two clock-bridge cells that carry a spine multiplexer -- cell
#: (54, 93) drives `SPINE8..13`, cell (54, 88) drives `SPINE16..21`.  A design
#: with one `DCE` lands on `SPINE8` in (54, 93) every time, so that cell is the
#: scope of the equivalence and `quadrant` is the sweep axis.
POINTS = {
    "q1": ((54, 93), "SPINE8"),
    "q2": ((54, 88), "SPINE16"),
}

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; the same 27 P1.T08d runs used it as "
              "reset")

E1_RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    input  wire cen,
    output wire [3:0] led
);

    wire gated_clk;

    // The primitive under test.  It is spelled DCE on this family; DQCE is
    // the pre-5A name and GowinSynthesis refuses it (EX3937).  Its whole
    // bitstream signature is the select fuse of one spine multiplexer in the
    // clock-bridge cell {cell} (P1.T29).
    DCE dce0 (
        .CLKIN  (clk),
        .CE     (cen),
        .CLKOUT (gated_clk)
    );

    // Context, NOT compared: a ring counter, deliberately not an adder, so the
    // `c1` decode check unpacks with noalu=True (MEASURED, P1.T14).  It is
    // what forces the gated clock onto the global clock network.
    reg [3:0] ring;
    always @(posedge gated_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


def e1_rtl(spec, sweep_value=None):
    value = sweep_value if sweep_value is not None else spec.baseline_value
    cell, _spine = POINTS[value]
    return E1_RTL.format(
        name=spec.name, primitive=spec.primitive, sweep_axis=spec.sweep_axis,
        sweep_value=value, top_module=spec.top_module, cell=cell)


def _spec():
    from . import PinSpec, ScopeSpec, ShapeSpec
    return ShapeSpec(
        name="clocking_dqce",
        primitive="DQCE",
        sweep_axis="quadrant",
        sweep_values=list(POINTS),
        baseline_value="q1",
        pins={
            "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                           config_role_ack=_ACK_CLK),
            "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                             direction="input", config_role_ack=_ACK_RESET),
            "cen": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None,
                           direction="input"),
            "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
            "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
            "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
            "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
        },
        bank_vccio={4: "3.3", 5: "3.3"},
        # Both clock-bridge cells: which of the two quadrants hosts the
        # DQCE is the router's choice, not the design's, so a scope of
        # one of them would compare an empty tile whenever the two
        # flows chose differently.
        scope=ScopeSpec(tiles=[[93, 54], [88, 54]]),
        rtl=e1_rtl,
        clocks={"clk": 20.0},
    )


SPEC = _spec()
