"""`clocking_clkdiv` -- the CLKDIV `DIV_MODE` sweep on the GW5AST-138C (`P1.T14`).

One `CLKDIV` whose `CLKOUT` clocks a 24-bit counter driving four LEDs, so the
divided clock must actually escape the HCLK block onto the global clock
network (`P1.T08d`).  The swept parameter is `DIV_MODE`, over the nine values
`gowin_pack.GW5A.get_valid_clkdiv_divmodes()` admits and UG306E p.25
documents: `1, 2, 3, 3.5, 4, 5, 6, 7, 8`.  The baseline is the same design at
the documented default `"2"` (`gowin_pack.py:5645-5646`), not an empty design.

**Both flows are pinned to the same site**, which is what makes `E1`
meaningful here:

* the vendor by `INS_LOC "div0" BOTTOMSIDE[4];` -- SUG1018-1.7E §2.9 Table 2-2
  row `GW5A(S)(T)-138`, and `P1.T08d` measured `BOTTOMSIDE[4..7]` -> HCLK
  block 5 at cell `(row 108, col 117)`;
* the open flow by the RTL `(* BEL = "X117Y108/CLKDIV_0" *)` attribute,
  because `nextpnr-himbaechel`'s `.cst` reader accepts only
  `{...}SIDE[0|1]` (`cst.cc:130-140`) and turns `BOTTOMSIDE[4]` into a fatal
  `Unknown placement macro`.  `gen.py` therefore writes the `INS_LOC` block
  into `top.cst` only and hands the open flow `top-open.cst`.

The unpinned control is the sibling shape `clocking_clkdiv_free`.

Pins are the `P1.T08d` set, unchanged so the whole `P1` CLKDIV evidence base
is one design family.  Two of them carry a config role and a MEASURED
`config_role_ack`:

    clk    V22  IOB104B  bank 4  EMCCLK      config-role, MEASURED ack
    reset  Y12  IOB60B   bank 5  SGCLKC_6    config-role, MEASURED ack
    led0-3 P20/Y17/W14/Y16  banks 4,5,5,5    no role at all

The LED pins are **not** `P1.T08d`'s `P19/R19/T21/U21`: those are the SSPI and
flash-data balls, and claiming them needs `-use_sspi_as_gpio 1` on the vendor
and `--sspi_as_gpio` on `gowin_pack` -- which MEASURED (`P1.T14` trial run
`p1t14-trial`) aborts the pack with `sspi_as_gpio has conflicting settings in
nexpnr and gowin_pack` (`gowin_pack.py:5386`), because the flag has to reach
nextpnr as `--vopt sspi_as_gpio` too and `openflow.nextpnr_command` has no
such hook.  Four ordinary bank-4/5 balls need no flag on either side, so the
shape uses those and the question does not arise.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: HCLK block 5 of the 138C: `chipdb._gw5a_hclk_locs['GW5AST-138C'][5]` is
#: `(row 108, col 117)`, so the Himbaechel site is `X117Y108` (`P1.T04`).
BLOCK5_XY = (117, 108)

#: `INS_LOC` index -> the same block/lane the `BEL` attribute names
#: (`P1.T08d`: `BOTTOMSIDE[4..7]` is block 5, lanes 0..3).
INS_LOC_INDEX = 4
LANE = 0

#: UG306E p.25 / `gowin_pack.GW5A.get_valid_clkdiv_divmodes()`.
DIV_MODES = ["1", "2", "3", "3.5", "4", "5", "6", "7", "8"]
DEFAULT_DIV_MODE = "2"

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/{name}.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire reset,
    output wire [3:0] led
);

    wire div_clk;

    // The primitive under test.  The BEL attribute pins the OPEN flow; the
    // vendor is pinned by INS_LOC "div0" BOTTOMSIDE[{ins_loc_index}] in top.cst.
    (* BEL = "X{bx}Y{by}/CLKDIV_{lane}" *) CLKDIV div0 (
        .HCLKIN (clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "{sweep_value}";

    // Context, NOT compared (the E0 scope is the HCLK block cell only): the
    // counter exists so CLKOUT must leave the block on the clock network.
    // A ring counter, deliberately NOT an adder: an adder packs into ALU
    // bels and the `c1` decode check unpacks the open bitstream with
    // `noalu=True`, so every ALU comes back missing (MEASURED, P1.T14 trial
    // run `p1t14-trial2`: 24 `c1_missing` ALU cells).  That is a gap in the
    // harness's ALU decode path, not a property of CLKDIV, and a shape whose
    // context is LUT+DFF only does not step on it.
    reg [3:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    return RTL.format(
        name=spec.name, primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value if sweep_value is not None else spec.baseline_value,
        top_module=spec.top_module,
        bx=BLOCK5_XY[0], by=BLOCK5_XY[1], lane=LANE,
        ins_loc_index=INS_LOC_INDEX)


#: The MEASURED evidence each config-role exemption rests on.
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on "
            "V22 and gw_sh returned 0 every time (P1.T08d "
            "evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board "
            "clock and examples/gw5a/tangmega138k.cst names it")
_ACK_RESET = ("SGCLKC_6: a dedicated global-clock input ball, not a "
              "configuration function; same 27 P1.T08d runs used it as reset")

SPEC = ShapeSpec(
    name="clocking_clkdiv",
    primitive="CLKDIV",
    sweep_axis="DIV_MODE",
    sweep_values=DIV_MODES,
    baseline_value=DEFAULT_DIV_MODE,
    pins={
        "clk": PinSpec(loc="V22", bank=4, drive=None, direction="input",
                       config_role_ack=_ACK_CLK),
        "reset": PinSpec(loc="Y12", bank=5, pull_mode="UP", drive=None,
                         direction="input", config_role_ack=_ACK_RESET),
        "led[0]": PinSpec(loc="P20", bank=4, direction="output"),
        "led[1]": PinSpec(loc="Y17", bank=5, direction="output"),
        "led[2]": PinSpec(loc="W14", bank=5, direction="output"),
        "led[3]": PinSpec(loc="Y16", bank=5, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[list(BLOCK5_XY)]),
    rtl=rtl,
    ins_loc={"div0": "BOTTOMSIDE[%d]" % INS_LOC_INDEX},
    clocks={"clk": 20.0},
)
