"""`diff_io` -- the differential IO types on the GW5AST-138C (`P3.T23`/`P3.T25`).

`TLVDS_IBUF`, `TLVDS_OBUF` and `TLVDS_TBUF`, then `ELVDS_OBUF`, `ELVDS_TBUF`
and `ELVDS_IOBUF`, one type per run, on the board's only true-LVDS pairs --
the HDMI TMDS pairs of bank 3 (`TRUELVDS` in the package pinout, and the only
`SAFE_PINS` entries with a `PAIR`).  UG304E documents no `ELVDS_IBUF`; the
input side of the E family is `ELVDS_IOBUF` (`spec-primitives.md` §2), so
that is what the sweep carries.

`TLVDS_IOBUF` is deliberately **absent**: `chipdb.fse_create_diff_types`
removes it for every device outside `{GW5A-25A, GW2A-18, GW2A-18C, GW1N-4}`
with no recorded rationale, and whether that removal is right on this die is
`P3.T24`'s adjudication against the oracle -- not something a shape may
presume either way.

**Known collision with the frozen `.cst` assertion.**  `harness/gen.py`'s
rules (a) and (b) require *every* used pin to carry an `IO_TYPE` and admit
only `LVCMOS33` on a non-DDR pin.  Both were written for single-ended pins,
before a differential shape existed, and both refuse a differential pad --
which the vendor's own `tang_mega_138K_pins.cst` gives no `IO_TYPE` at all.
Granting them a differential exemption is a `harness/gen.py` change, and
`harness/**` is Phase 0's and frozen for Phase 3 (`P3.T10` "Must NOT
change"), so this shape spells the pads as the vendor does and `P3.T23`
carries the harness amendment as its first step.  `test_io_shapes_138c.py`
pins the collision so it is a named, measured gap rather than a surprise at
batch time.
"""
from ._io_base import IoShape

#: The buffer primitive per sweep point -- one type per run, and the swept
#: axis *is* the type identity.  The pads carry no `IO_TYPE`: a differential
#: standard comes from the primitive, which is how the vendor's own board
#: constraints spell the TMDS pairs.  (`LVDS25E`, sometimes quoted as an
#: ELVDS requirement, is only apicula's default `IO_TYPE` for an ELVDS buffer
#: -- `gowin_pack.py:1658-1660`, `spec-primitives.md:125` -- and the real
#: vendor `IO_TYPE`/VCCIO matrix is recorded from the oracle by `P3.T25`.)
POINTS = {
    "tlvds-ibuf": "TLVDS_IBUF",
    "tlvds-obuf": "TLVDS_OBUF",
    "tlvds-tbuf": "TLVDS_TBUF",
    "elvds-obuf": "ELVDS_OBUF",
    "elvds-tbuf": "ELVDS_TBUF",
    "elvds-iobuf": "ELVDS_IOBUF",
}

BASELINE = "tlvds-obuf"

#: Ports of each type (`cells_sim.v:585,593`, `cells_xtra_gw5a.v:45-70`).
#: Written out rather than inferred: an `IOBUF`'s `IO`/`IOB` are `inout` and
#: a `TBUF`'s are `output`, and getting that wrong changes which pad fuses
#: the vendor sets.
_BODIES = {
    "TLVDS_IBUF": """\
    TLVDS_IBUF dut (
        .O  (rx),
        .I  (pad_p),
        .IB (pad_n)
    );
""",
    "TLVDS_OBUF": """\
    TLVDS_OBUF dut (
        .I  (tx),
        .O  (pad_p),
        .OB (pad_n)
    );
""",
    "TLVDS_TBUF": """\
    TLVDS_TBUF dut (
        .I   (tx),
        .OEN (oen),
        .O   (pad_p),
        .OB  (pad_n)
    );
""",
    "ELVDS_OBUF": """\
    ELVDS_OBUF dut (
        .I  (tx),
        .O  (pad_p),
        .OB (pad_n)
    );
""",
    "ELVDS_TBUF": """\
    ELVDS_TBUF dut (
        .I   (tx),
        .OEN (oen),
        .O   (pad_p),
        .OB  (pad_n)
    );
""",
    "ELVDS_IOBUF": """\
    ELVDS_IOBUF dut (
        .O   (rx),
        .IO  (pad_p),
        .IOB (pad_n),
        .I   (tx),
        .OEN (oen)
    );
""",
}

#: Which direction each type gives the pad pair, which is what the `.cst`
#: renders and what `DRIVE` is legal on (`CT1108`, measured `P0.T19`).
PAD_DIRECTION = {
    "TLVDS_IBUF": "input",
    "TLVDS_OBUF": "output",
    "TLVDS_TBUF": "output",
    "ELVDS_OBUF": "output",
    "ELVDS_TBUF": "output",
    "ELVDS_IOBUF": "output",
}

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/diff_io.py -- do not edit.
// Shape: diff_io (primitive under test: {primitive})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire clk,
    input  wire din,
    input  wire oen,
    output wire dout,
    {pad_decl} wire pad_p,
    {pad_decl} wire pad_n
);

    wire rx;
    reg  tx, seen;

    // Both sides are registered so neither the driver nor the receiver is a
    // constant the synthesiser can fold, which would leave the buffer
    // unrealised and nothing to diff.
    always @(posedge clk) begin
        tx   <= din;
        seen <= rx;
    end

    assign dout = seen;

{body}
endmodule

`default_nettype wire
"""


class DiffIoShape(IoShape):
    """One differential buffer per run on the board's TMDS pairs."""

    name = "diff_io"
    primitive = "TLVDS_*/ELVDS_*"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "clk": ("V22", "input"),
        "din": ("N15", "input"),
        "oen": ("AB13", "input", {"pull_mode": "UP"}),
        "dout": ("P20", "output"),
        # No `DRIVE` and no `IO_TYPE` on the pads: the swept axis changes the
        # pair's direction (an `IBUF` point reads them, an `OBUF` point drives
        # them) while `ShapeSpec.pins` is fixed for the whole sweep, so the
        # shape emits nothing direction-dependent -- `DRIVE` on an input is
        # `CT1108` (measured `P0.T19`).
        "pad_p": ("J14", "output", {"io_type": None, "drive": None}),
        "pad_n": ("H14", "output", {"io_type": None, "drive": None}),
    }
    diff_pads = ("pad_p", "pad_n")
    clocks = {"clk": 20.0}
    config_role_acks = {"V22": _ACK_CLK}

    def rtl(self, sweep_value):
        primitive = POINTS[sweep_value]
        direction = PAD_DIRECTION[primitive]
        pad_decl = {"input": "input ", "output": "output",
                    "inout": "inout "}[direction]
        return _TEMPLATE.format(
            primitive=primitive, axis=self.sweep_axis, point=sweep_value,
            top=self.top_module, pad_decl=pad_decl,
            body=_BODIES[primitive])


SPEC = DiffIoShape().spec()
