"""`dualpin` -- one dual-purpose-pin option at a time (`P2.T28`).

The GW5AST-138C shares eight of its configuration ports with fabric I/O.  A
build hands a port to the fabric by asking for it in **two** namespaces that
must never be confused (`F34`):

* the vendor's Tcl, `set_option -use_<opt>_as_gpio 1`;
* `gowin_pack`'s command line, `--<opt>_as_gpio`.

Two of them, `sspi` and `i2c`, are also declared to `nextpnr-himbaechel` as
`--vopt <opt>_as_gpio`, because `gowin_pack` cross-checks the packer flag
against the placed netlist and raises when the two disagree.

This shape is the vehicle that measures what each option costs in fuses.  It
is deliberately the smallest design that still has a placed, pinned primitive:
one input, one flop, one LED, with the flop pinned by `INS_LOC` so the `E0`
scope is a single tile and the comparison has something to assert.  The
*design* is constant across the sweep; only the option set moves, so every bit
that differs between a point and the baseline is attributable to that option
and nothing else.

**Which side of the mask this shape sits on.**  It is a configuration shape,
not an I/O shape: the swept parameter is a chip-level configuration attribute,
and the three pins are context held fixed.  `dontcare.mask`'s IO-default entry
is therefore left exactly as it is -- masking anything here would erase the
very bits the sweep exists to find.

Ten harness runs: the all-off baseline, then the nine sweep points -- each of
the eight options alone, then the `{sspi, mspi, cpu}` triple a real AE350
design needs (step (4) of the `AE350_SOC` recipe).  The triple is measured as
a point of its own because superposition of three independent option sets is a
claim, not an assumption.

Pins are in banks 4 and 5 -- never 6 or 7 (`D20c`, `D54`, `F73`/PR #423) -- and
are the package locations `shapes/smoke.py` already ran through the vendor
without tripping the config-role refusal.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

#: Every option this device shares between configuration and fabric, in the
#: order `gowin_pack.CliArgs` declares them.  `mode` is deliberately absent:
#: the vendor accepts `-use_mode_as_gpio`, apicula defines no flag for it, and
#: this sweep measures only what both flows can express.
OPTIONS = ("jtag", "sspi", "mspi", "ready", "done", "reconfign", "cpu", "i2c")

#: The options a bare AE350 design hands to the fabric (`P2.T20`, step (4) of
#: the `AE350_SOC` recipe).
AE350_TRIPLE = ("sspi", "mspi", "cpu")

#: The all-off point every sweep point is diffed against.
BASELINE = "none"

#: The nine sweep points, in run order: the eight singles, then the triple.
SWEEP_POINTS = list(OPTIONS) + ["ae350_triple"]

#: The two options `nextpnr-himbaechel` also has to be told about, because
#: `gowin_pack` refuses a packer flag the placed netlist does not corroborate.
NEXTPNR_KNOWN = ("sspi", "i2c")

#: MEASURED (`P2.T29`): does `CPU_AS_GPIO_2` (`attrids` handle 37) move a bit
#: on this device?  `gowin_pack.GW5AST_138C.get_pins_attr_vals` emits the
#: attribute if and only if this is true, and `tests/test_dualpin_138c.py`
#: asserts the two agree.
CPU_AS_GPIO_2_SETS_A_BIT = False


def options_of(sweep_value):
    """The options turned on at one sweep point, as a tuple of bare names."""
    if sweep_value in (None, BASELINE):
        return ()
    if sweep_value == "ae350_triple":
        return AE350_TRIPLE
    if sweep_value in OPTIONS:
        return (sweep_value,)
    raise ValueError(f"unknown dualpin sweep point: {sweep_value!r}")


def gwsh_options(spec, sweep_value=None):
    """The vendor namespace: `-use_<opt>_as_gpio 1`, never `--<opt>_as_gpio`."""
    return [f"-use_{opt}_as_gpio 1" for opt in options_of(sweep_value)]


def pack_flags(spec, sweep_value=None):
    """The packer namespace: `--<opt>_as_gpio`, never `-use_...`."""
    return [f"--{opt}_as_gpio" for opt in options_of(sweep_value)]


def nextpnr_vopts(spec, sweep_value=None):
    """The `--vopt` names, for the two options nextpnr knows (bare, no dashes)."""
    return [f"{opt}_as_gpio" for opt in options_of(sweep_value)
            if opt in NEXTPNR_KNOWN]


RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/dualpin.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}  (options on: {options})
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire din,
    output wire led
);

    // The primitive under test: one flop, pinned by INS_LOC so its tile is
    // deterministic and the E0 scope is exactly that tile.  The design is
    // identical at every sweep point -- only the configuration options move.
    wire dut_q;
    DFF dut_dff (
        .D   (din),
        .CLK (clk),
        .Q   (dut_q)
    );

    assign led = dut_q;

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    """Render this shape's Verilog for one sweep point."""
    return RTL.format(
        name=spec.name,
        primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value if sweep_value is not None else spec.baseline_value,
        options=",".join(options_of(sweep_value)) or "-",
        top_module=spec.top_module,
    )


SPEC = ShapeSpec(
    name="dualpin",
    primitive="DFF",
    sweep_axis="dual_purpose_option",
    sweep_values=[BASELINE] + SWEEP_POINTS,
    baseline_value=BASELINE,
    pins={
        "clk": PinSpec(loc="AA9", bank=5, drive=None, direction="input"),
        "din": PinSpec(loc="AA11", bank=5, pull_mode="UP", drive=None,
                       direction="input"),
        "led": PinSpec(loc="P20", bank=4, direction="output"),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[(2, 1)]),
    rtl=rtl,
    ins_loc={"dut_dff": "R2C3[0][A]"},
    clocks={"clk": 20.0},
    extra_gwsh_options=gwsh_options,
    extra_pack_flags=pack_flags,
    extra_nextpnr_vopts=nextpnr_vopts,
)
