"""`io_basic_b` -- an `ODDRC` on the **B** half of a pad pair (`P3.F3`).

Every other Phase-3 IOLOGIC point sits on an `A`-half ball, because `P3.T11`
read a zero out of `db.shortval[247]['IOLOGICB']` -- a three-coordinate stub --
and published it as "an IOLOGIC is configurable on the A half only".  That
reason is retracted: the hundred-coordinate `IOLOGICB` table lives in the
**adjacent aux cell** (`ttyp` 248, the pad's own `fuse_cell_offset`), which is
where the vendor writes a `B` half's IOLOGIC fuses and where
`chipdb.gw5_displace_iologicb` now sends the open flow's.

This shape is the measurement that claim owes: one `ODDRC` on `AB17`
(`IOB80B`, cell `(108,79)`, aux cell `(108,80)`), the very ball whose silence
the retracted conclusion rested on.  The pair's `A` half is left empty on
purpose -- a `B` half that configures only when its `A` neighbour does would
not be a usable column.

`ODDRC` rather than `ODDR`: `AB17` is the ball `P3.T11` put `ODDRC` on, so this
run answers the same question with the same primitive on the same pad.

Every net of the scoped tiles ends on a package ball (`D105`), as in
`io_basic`: an unregistered `D1`/`D0` off two pads and the spare outputs
driven straight through, so no freely placed fabric cell can give a scoped net
two identities.
"""
from ._io_base import IoShape

#: One point: the whole question is whether the `B` half configures at all.
POINTS = {"oddrc-default": ("ODDRC", {})}

BASELINE = "oddrc-default"

#: The pad under test and the balls around it, all bank 5 (`P3.T06`'s measured
#: pin table, `$OTC/evidence/iologic/pin-hclk-138c.json`).
DUT_BALL = "AB17"          # IOB80B, cell (108,79) B half, aux cell (108,80)
CLK_BALL = "V22"           # the board oscillator
DATA_IN_BALL = "AA15"      # IOB83A
DATA_D1_BALL = "T16"       # IOB76A
CLEAR_BALL = "AB13"        # IOB89B, Key_in[0]
SPARE_D1_BALL = "W16"      # IOB72B
SPARE_IN_BALL = "Y16"      # IOB78A

#: Both cells a `B`-half IOLOGIC touches: its pad's own cell, which carries the
#: bel, and the aux cell one column on, which carries its fuses.  A scope
#: naming only the first would compare the pad and miss every IOLOGIC fuse the
#: run is about.  `(x, y)` = `(col, row)`, the Himbaechel spelling.
SCOPE_TILES = ((79, 108), (80, 108))

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_basic_b.py -- do not edit.
// Shape: io_basic_b (primitive under test: {primitive}, B half of the pad pair)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire clk,
    input  wire din,
    input  wire d1,
    input  wire clear,
    output wire dout,
    output wire dout2,
    output wire dout3
);

    {primitive} dut (
        .D0    (din),
        .D1    (d1),
        .TX    (1'b0),
        .CLK   (clk),
        .CLEAR (clear),
        .Q0    (dout),
        .Q1    ()
    );
{defparams}\
    // Both serialiser inputs come off pads and Q0 drives one, so every net of
    // the scoped tiles has both its endpoints at an `IO_LOC`-pinned site.
    assign dout2 = d1;
    assign dout3 = din;

endmodule

`default_nettype wire
"""


class IoBasicBShape(IoShape):
    """`ODDRC` in the `B` half of a pad pair, clocked from the board clock."""

    name = "io_basic_b"
    #: The table row this shape's evidence joins to.  The point is an
    #: `ODDRC` on the `B` half; the row it belongs to is the `ODDR / IDDR`
    #: one, and the ball and half are carried in `sweep`, not in the id.
    primitive = "ODDR / IDDR"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "clk": (CLK_BALL, "input"),
        "din": (DATA_IN_BALL, "input"),
        "d1": (DATA_D1_BALL, "input"),
        "clear": (CLEAR_BALL, "input", {"pull_mode": "DOWN"}),
        "dout": (DUT_BALL, "output"),
        "dout2": (SPARE_D1_BALL, "output"),
        "dout3": (SPARE_IN_BALL, "output"),
    }
    clocks = {"clk": 20.0}
    config_role_acks = {CLK_BALL: _ACK_CLK}
    scope_tiles = SCOPE_TILES

    def rtl(self, sweep_value):
        primitive, defparams = POINTS[sweep_value]
        rendered = "".join('    defparam dut.%s = %s;\n' % (key, value)
                           for key, value in sorted(defparams.items()))
        return _TEMPLATE.format(primitive=primitive, axis=self.sweep_axis,
                                point=sweep_value, top=self.top_module,
                                defparams=rendered)


SPEC = IoBasicBShape().spec()
