"""`io_basic` -- the `ODDR`/`IDDR` sweep on the GW5AST-138C (`P3.T11`/`P3.T12`).

One `ODDR` on an output ball and one `IDDR` on an input ball, both clocked
from the board clock on `V22`, sweeping one attribute per run over the two
primitives' whole documented parameter sets (`cells_sim.v:856` `IDDR(D, CLK,
Q0, Q1)` with `Q0_INIT`/`Q1_INIT`, `:898` `ODDR(D0, D1, TX, CLK, Q0, Q1)` with
`TXCLK_POL`/`INIT`).  The baseline is the same design at the documented
defaults, never an empty design, so a moved fuse is the attribute's.

Both IO balls are **bank 4**, the bank the board clock itself is in: the
`P3.T06` table puts every bank-4 ball on HCLK block 5, so an `FCLK` that is
proven to reach the IOLOGIC of one bank-4 ball is proven for the others.
That is the property `P3.T07` measures; until it has, this shape's clock
routing is the hypothesis under test, which is exactly what a fuzzing shape
should be.

The design keeps a fabric flop on each side so the IOLOGIC has a real
producer and consumer -- an unconnected `IDDR` output is optimised away and
the vendor then realises no IOLOGIC at all.
"""
from ._io_base import IoShape

#: `(primitive, defparams)` per sweep point.  One axis moves per run
#: (`F12`), which is what lets `attribute.py` attribute a moved fuse.
POINTS = {
    "oddr-default": ("ODDR", {}),
    "oddr-txclk-pol": ("ODDR", {"TXCLK_POL": "1"}),
    "oddr-init": ("ODDR", {"INIT": "1"}),
    "iddr-default": ("IDDR", {}),
    "iddr-q0-init": ("IDDR", {"Q0_INIT": "1'b1"}),
    "iddr-q1-init": ("IDDR", {"Q1_INIT": "1'b1"}),
}

BASELINE = "oddr-default"

#: The MEASURED evidence the `V22` config-role exemption rests on.
_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_ODDR_RTL = """\
    ODDR dut (
        .D0  (d0),
        .D1  (d1),
        .TX  (1'b0),
        .CLK (clk),
        .Q0  (q0),
        .Q1  ()
    );
{defparams}\
    assign dout = q0;
    always @(posedge clk) begin
        d0 <= din_r;
        d1 <= ~din_r;
    end
"""

_IDDR_RTL = """\
    IDDR dut (
        .D   (din_r),
        .CLK (clk),
        .Q0  (q0),
        .Q1  (q1)
    );
{defparams}\
    always @(posedge clk)
        dout_r <= q0 ^ q1;
    assign dout = dout_r;
"""

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_basic.py -- do not edit.
// Shape: io_basic (primitive under test: {primitive})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire clk,
    input  wire din,
    output wire dout
);

    wire q0, q1;
    reg  d0, d1;
    reg  din_r, dout_r;

    // Registered on both sides so the IOLOGIC has a real producer and
    // consumer; an unconnected gearbox output is optimised away and the
    // vendor then realises no IOLOGIC at all.
    always @(posedge clk)
        din_r <= din;

{body}
endmodule

`default_nettype wire
"""


class IoBasicShape(IoShape):
    """`ODDR` and `IDDR` on two bank-4 balls, clocked from the board clock."""

    name = "io_basic"
    primitive = "ODDR/IDDR"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "clk": ("V22", "input"),
        "din": ("N15", "input"),
        "dout": ("P20", "output"),
    }
    clocks = {"clk": 20.0}
    config_role_acks = {"V22": _ACK_CLK}

    def rtl(self, sweep_value):
        primitive, defparams = POINTS[sweep_value]
        rendered = "".join('    defparam dut.%s = %s;\n' % (key, value)
                           for key, value in sorted(defparams.items()))
        body = (_ODDR_RTL if primitive == "ODDR" else _IDDR_RTL).format(
            defparams=rendered)
        return _TEMPLATE.format(primitive=primitive, axis=self.sweep_axis,
                                point=sweep_value, top=self.top_module,
                                body=body)


SPEC = IoBasicShape().spec()
