"""`io_des` -- the input-deserialiser family on the GW5AST-138C (`P3.T14`).

`IDES4`, `IDES8` and `IDES10`, one per run, on the dock's RGMII side, which is
the RX half of `S10`: an RGMII receiver is a 1:2 input gearbox clocked from
the PHY's `RXC`.

The divider is the whole point of the shape and the thing most easily got
wrong, so it is stated once and derived everywhere: a `w`-bit gearbox's
`PCLK` is `FCLK / (w / 2)` (UG304E p.62-69) -- `IDES4` at half, `IDES8` at a
quarter, `IDES10` at a fifth.  `_io_base.GEARBOX_DIV_MODE` holds those and
the `.sdc` declares both clocks, so a wrong divider fails timing rather than
passing quietly with a mis-sampled word.

`FCLK` comes from the board clock and `PCLK` from a `CLKDIV` in HCLK block 5,
for the reason `io_ser` gives: `CLKDIV` is closed at `E1` on this die and the
PLL->HCLK path is not.
"""
from ._io_base import GEARBOX_DIV_MODE, IoShape, clkdiv_rtl

#: `(width, attribute, value)` per sweep point, one axis per run (`F12`).
POINTS = {
    "ides4-default": (4, None, None),
    "ides4-lsren": (4, "LSREN", '"false"'),
    "ides8-default": (8, None, None),
    "ides8-lsren": (8, "LSREN", '"false"'),
    "ides10-default": (10, None, None),
    "ides10-gsren": (10, "GSREN", '"true"'),
}

BASELINE = "ides4-default"

PRIMITIVE_OF_WIDTH = {4: "IDES4", 8: "IDES8", 10: "IDES10"}

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_des.py -- do not edit.
// Shape: io_des (primitive under test: {primitive})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire fclk,
    input  wire resetn,
    input  wire din,
    output wire dout
);

    wire pclk;
    wire [{msb}:0] word;
    reg  parity;

{clkdiv}
    {primitive} dut (
{ports}    );
{defparams}
    // The whole word is reduced into one pin so no bit of it is dead: an
    // unused deserialiser output is optimised away and the vendor then
    // realises a narrower gearbox than the one under test.
    always @(posedge pclk)
        parity <= ^word;

    assign dout = parity;

endmodule

`default_nettype wire
"""


def _port_block(width):
    lines = ["        .%-6s (word[%d])," % ("Q%d" % i, i)
             for i in range(width - 1, -1, -1)]
    lines += [
        "        .FCLK   (fclk),",
        "        .PCLK   (pclk),",
        "        .RESET  (~resetn),",
        "        .CALIB  (1'b0),",
        "        .D      (din)",
    ]
    return "\n".join(lines) + "\n"


class IoDesShape(IoShape):
    """One input deserialiser per run on the dock's RGMII balls."""

    name = "io_des"
    primitive = "IDES4/IDES8/IDES10"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "fclk": ("V22", "input"),
        "resetn": ("AB13", "input", {"pull_mode": "UP"}),
        "din": ("D21", "input"),
        "dout": ("F20", "output"),
    }
    clocks = {"fclk": 8.0}
    config_role_acks = {"V22": _ACK_CLK}

    def rtl(self, sweep_value):
        width, attribute, value = POINTS[sweep_value]
        primitive = PRIMITIVE_OF_WIDTH[width]
        defparams = ("    defparam dut.%s = %s;\n" % (attribute, value)
                     if attribute else "")
        return _TEMPLATE.format(
            primitive=primitive, axis=self.sweep_axis, point=sweep_value,
            top=self.top_module, msb=width - 1,
            clkdiv=clkdiv_rtl(width), ports=_port_block(width),
            defparams=defparams)


#: A width with no `DIV_MODE` would clock the gearbox wrong in silence.
assert set(PRIMITIVE_OF_WIDTH) <= set(GEARBOX_DIV_MODE)

SPEC = IoDesShape().spec()
