"""`io_des16_balls` -- the `E1` shape for the 16:1 input deserialiser (`P3.T16a`).

`io_des16` adjudicated the primitive (`P3.T16`) and could not close `conns`:
bank 5 brings out ten free balls and not sixteen, so that shape XOR-reduces
`Q10`-`Q15` onto one, and a fabric LUT is placed freely by each flow, giving a
scoped net two identities (`D105`).

This shape drops the reduction instead of hiding it.  `Q10`-`Q15` are simply
left unconnected: `IDES16` is a hard block, so an unused fabric output is a
wire nobody drives rather than logic that disappears, and every net the design
does hold starts or ends on a package ball.  The design therefore holds **no
fabric cell at all**, which is what `E1` on `conns` needs.

What the row loses by not observing all sixteen bits is nothing this level
measures: `E1` compares cells, attributes, placement and the scoped fuses, and
the sixteen-bit word is one `INMODE` value either way -- MEASURED (`P3.T16a`),
the vendor's `IDES16` differs from its `IDES4`/`IDES8`/`IDES10` in that one
attribute and in nothing else.
"""
from ._io_base import GEARBOX_CLKDIV_INS_LOC, IoShape

#: One point: the 16-bit word is one `INMODE` value, and `IDES16` has no
#: parameter of its own to sweep (`prim_sim.v:8906`).
POINTS = {"ides16-balls": 16}

BASELINE = "ides16-balls"

IDES_BALL = "AA9"          # IOB53A, cell (108,52), sk9822_da
RESET_BALL = "T16"         # IOB76A, LCD_CTP[2]
RESETN_BALL = "AB13"       # IOB89B, Key_in[0], the CLKDIV's own reset
FCLK_BALL = "V22"          # IOB104B, the board oscillator

#: One ball per bit for the low ten bits of the word; `Q10`-`Q15` stay open.
WORD_BALLS = ("Y17", "W14", "Y14", "Y16", "AA16",
              "AB16", "AB17", "AA15", "W15", "W16")

DIV_MODE = "8"

SCOPE_TILES = ((52, 108),)

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_des16_balls.py -- do not edit.
// Shape: io_des16_balls (primitive under test: IDES16)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din,
{word_ports});

    wire pclk;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "{div_mode}";

    IDES16 dut (
{ports}    );

endmodule

`default_nettype wire
"""


def _port_block():
    lines = ["        .%-6s (q%d)," % ("Q%d" % i, i)
             for i in range(9, -1, -1)]
    lines += [
        "        .FCLK   (fclk),",
        "        .PCLK   (pclk),",
        "        .RESET  (rst),",
        "        .CALIB  (1'b0),",
        "        .D      (din)",
    ]
    return "\n".join(lines) + "\n"


class IoDes16BallsShape(IoShape):
    """One `IDES16` on a bank-5 ball of HCLK block 4, balls only."""

    name = "io_des16_balls"
    primitive = "IDES16"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = dict(
        {
            "fclk": (FCLK_BALL, "input"),
            "resetn": (RESETN_BALL, "input", {"pull_mode": "UP"}),
            "rst": (RESET_BALL, "input", {"pull_mode": "DOWN"}),
            "din": (IDES_BALL, "input"),
        },
        **{"q%d" % i: (ball, "output")
           for i, ball in enumerate(WORD_BALLS)},
    )
    clocks = {"fclk": 8.0}
    config_role_acks = {FCLK_BALL: _ACK_CLK}
    scope_tiles = SCOPE_TILES
    ins_loc = {"pclk_div": GEARBOX_CLKDIV_INS_LOC}

    def rtl(self, sweep_value):
        word_ports = "".join(
            "    output wire q%d%s\n"
            % (i, "," if i < len(WORD_BALLS) - 1 else "")
            for i in range(len(WORD_BALLS)))
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            word_ports=word_ports, div_mode=DIV_MODE, ports=_port_block())


SPEC = IoDes16BallsShape().spec()
