"""`io_des16` -- the 16:1 input deserialiser adjudication on the 138C (`P3.T16`).

The mirror of `io_ser16`.  `IDES16` is declared in the vendor's GW5A
simulation library (`$GOWINHOME/IDE/simlib/gw5a/prim_sim.v:8906`,
`IDES16 (Q0..Q15, D, CALIB, PCLK, FCLK, RESET)`) and absent from the yosys
GW5A cell library, which declares `IDES14` and `IDES32` and no `IDES16`.
One vendor run decides whether the die has it; the exact vendor text is the
deliverable either way (`D30`).

**Ten of the sixteen output bits leave on their own ball and the remaining
six are reduced onto one.**  Bank 5 brings out eleven balls this shape has
not already claimed, not sixteen, and `SAFE_PINS` is an allowlist by
construction (`_io_base`).  The reduction is a fabric LUT, so this shape is
**not** `D105`-clean and cannot reach `E1` on `conns`: a freely placed LUT
gives the scoped tile's nets two identities.  That is deliberate and costs
nothing here, because the row this shape exists to produce is an
*adjudication* -- accepted or refused by name -- and an acceptance raises a
follow-up task that builds the `E1` shape properly.  An `E0` row is recorded
with the reason if the vendor accepts.
"""
from ._io_base import GEARBOX_CLKDIV_INS_LOC, IoShape

POINTS = {"ides16-default": 16}

BASELINE = "ides16-default"

IDES_BALL = "AA9"          # IOB53A, cell (108,52), sk9822_da
RESET_BALL = "T16"         # IOB76A, LCD_CTP[2]
RESETN_BALL = "AB13"       # IOB89B, Key_in[0], the CLKDIV's own reset
FCLK_BALL = "V22"          # IOB104B, the board oscillator

#: One ball per bit for the low ten bits of the word.
WORD_BALLS = ("Y17", "W14", "Y14", "Y16", "AA16",
              "AB16", "AB17", "AA15", "W15", "W16")

#: The one ball the high six bits share, through a reduction LUT.
FOLD_BALL = "Y13"          # IOB87A, cmos_sda

DIV_MODE = "8"

SCOPE_TILES = ((52, 108),)

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_des16.py -- do not edit.
// Shape: io_des16 (primitive under test: IDES16)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din,
    output wire fold,
{word_ports});

    wire pclk;
    wire [15:10] qhi;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "{div_mode}";

    IDES16 dut (
{ports}    );

    // Bank 5 brings out ten free balls, not sixteen: the high six bits are
    // reduced onto one.  See the module docstring -- this costs `conns`.
    assign fold = ^qhi;

endmodule

`default_nettype wire
"""


def _port_block():
    lines = ["        .%-6s (qhi[%d])," % ("Q%d" % i, i)
             for i in range(15, 9, -1)]
    lines += ["        .%-6s (q%d)," % ("Q%d" % i, i)
              for i in range(9, -1, -1)]
    lines += [
        "        .FCLK   (fclk),",
        "        .PCLK   (pclk),",
        "        .RESET  (rst),",
        "        .CALIB  (1'b0),",
        "        .D      (din)",
    ]
    return "\n".join(lines) + "\n"


class IoDes16Shape(IoShape):
    """One `IDES16` on a bank-5 ball of HCLK block 4."""

    name = "io_des16"
    primitive = "OSER16 / IDES16"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = dict(
        {
            "fclk": (FCLK_BALL, "input"),
            "resetn": (RESETN_BALL, "input", {"pull_mode": "UP"}),
            "rst": (RESET_BALL, "input", {"pull_mode": "DOWN"}),
            "din": (IDES_BALL, "input"),
        },
        **{"q%d" % i: (ball, "output")
           for i, ball in enumerate(WORD_BALLS)},
        fold=(FOLD_BALL, "output"),
    )
    clocks = {"fclk": 8.0}
    config_role_acks = {FCLK_BALL: _ACK_CLK}
    scope_tiles = SCOPE_TILES
    ins_loc = {"pclk_div": GEARBOX_CLKDIV_INS_LOC}

    def rtl(self, sweep_value):
        word_ports = "".join(
            "    output wire q%d%s\n"
            % (i, "," if i < len(WORD_BALLS) - 1 else "")
            for i in range(len(WORD_BALLS)))
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            word_ports=word_ports, div_mode=DIV_MODE, ports=_port_block())


SPEC = IoDes16Shape().spec()
