"""`io_ser` -- the output-serialiser family on the GW5AST-138C (`P3.T13`).

`OSER4`, `OSER8`, `OSER10` and `OVIDEO`, one per run, on the dock's RGMII
side (bank 2) because that is where a serialiser has a reason to exist on
this board: `RGMII_TXD[3:0]` and `RGMII_GTXCLK` are the nets a 2:1 output
gearbox drives at 125 MHz, and proving the family there proves the RGMII TX
half of `S10`.

`FCLK` is the board clock and `PCLK` is that clock divided in HCLK block 5 by
a `CLKDIV` -- the gearbox's slow clock is `FCLK / (width / 2)` (UG304E
p.62-69), which is `DIV_MODE` `2`, `3.5`, `4` and `5` for widths 4, 7, 8 and
10.  `CLKDIV` is used rather than a PLL because Phase 1 closed it at `E1` on
this die and the PLL->HCLK path is a Phase-1 gap; a shape should not rest on
an unproven primitive to test a different one.

The swept axis is `TXCLK_POL` and `LSREN`, one per run per width, which with
four widths is the eight runs `spec-primitives.md` §2 budgets.  `OSER10` and
`OVIDEO` expose no `TXCLK_POL` (`cells_sim.v:662`/`:683` declare only `GSREN`
and `LSREN`), so their second point moves `GSREN` instead -- the sweep stays
one axis per run either way.
"""
from ._io_base import GEARBOX_DIV_MODE, IoShape, clkdiv_rtl

#: `(width, attribute, value)` per sweep point, one axis per run (`F12`).
POINTS = {
    "oser4-default": (4, None, None),
    "oser4-txclk-pol": (4, "TXCLK_POL", "1"),
    "oser8-default": (8, None, None),
    "oser8-txclk-pol": (8, "TXCLK_POL", "1"),
    "oser10-default": (10, None, None),
    "oser10-lsren": (10, "LSREN", '"false"'),
    "ovideo-default": (7, None, None),
    "ovideo-lsren": (7, "LSREN", '"false"'),
}

BASELINE = "oser4-default"

#: The primitive each gearbox width names.
PRIMITIVE_OF_WIDTH = {4: "OSER4", 7: "OVIDEO", 8: "OSER8", 10: "OSER10"}

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_ser.py -- do not edit.
// Shape: io_ser (primitive under test: {primitive})
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire fclk,
    input  wire resetn,
    input  wire din,
    output wire dout
);

    wire pclk;
    reg [{msb}:0] word;

{clkdiv}
    // The parallel word is a ring seeded from a real input pin, so no bit of
    // it is a constant the synthesiser can fold into the gearbox.
    always @(posedge pclk)
        word <= {{word[{msb1}:0], din}};

    {primitive} dut (
{ports}    );
{defparams}
endmodule

`default_nettype wire
"""


def _port_block(width, primitive):
    lines = ["        .%-6s (word[%d])," % ("D%d" % i, i)
             for i in range(width - 1, -1, -1)]
    if primitive in ("OSER4", "OSER8"):
        # TX0..TX(width/2-1) drive the pad's output enable; a serialiser that
        # never enables its pad realises no output buffer.
        lines += ["        .%-6s (1'b1)," % ("TX%d" % i)
                  for i in range(width // 2 - 1, -1, -1)]
    lines += [
        "        .FCLK   (fclk),",
        "        .PCLK   (pclk),",
        "        .RESET  (~resetn),",
    ]
    if primitive in ("OSER4", "OSER8"):
        lines += ["        .Q0     (dout),", "        .Q1     ()"]
    else:
        lines += ["        .Q      (dout)"]
    return "\n".join(lines) + "\n"


class IoSerShape(IoShape):
    """One output serialiser per run on the dock's RGMII balls."""

    name = "io_ser"
    primitive = "OSER4/OSER8/OSER10/OVIDEO"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "fclk": ("V22", "input"),
        "resetn": ("AB13", "input", {"pull_mode": "UP"}),
        "din": ("F21", "input"),
        "dout": ("F20", "output"),
    }
    clocks = {"fclk": 8.0}
    config_role_acks = {"V22": _ACK_CLK}
    ins_loc = {}

    def rtl(self, sweep_value):
        width, attribute, value = POINTS[sweep_value]
        primitive = PRIMITIVE_OF_WIDTH[width]
        defparams = ("    defparam dut.%s = %s;\n" % (attribute, value)
                     if attribute else "")
        return _TEMPLATE.format(
            primitive=primitive, axis=self.sweep_axis, point=sweep_value,
            top=self.top_module, msb=width - 1, msb1=width - 2,
            clkdiv=clkdiv_rtl(width), ports=_port_block(width, primitive),
            defparams=defparams)


#: Sanity that the module's two tables agree -- a width with no `DIV_MODE`
#: would render a `CLKDIV` with no divider and silently clock the gearbox
#: wrong.
assert set(PRIMITIVE_OF_WIDTH) == set(GEARBOX_DIV_MODE)

SPEC = IoSerShape().spec()
