"""`io_ser16` -- the 16:1 output serialiser adjudication on the 138C (`P3.T16`).

`OSER16` is **declared** in the vendor's own GW5A simulation library
(`$GOWINHOME/IDE/simlib/gw5a/prim_sim.v:11595`,
`OSER16 (Q, D0..D15, PCLK, FCLK, RESET)`) and is **absent** from the yosys
GW5A cell library (`cells_xtra_gw5a.v` declares `OSER14` and no `OSER16`),
so neither library settles whether the *silicon* of this die has a 16-bit
gearbox: a `prim_sim` module is a behavioural model, and yosys' cell list is
itself derived from a vendor edition that may predate the part.  One vendor
run decides it, and the exact vendor text is the deliverable either way
(`D30`).

The shape is `io_ser` at width 16 with `CLKDIV.DIV_MODE = "8"` (a 16-bit
gearbox runs its slow clock at `FCLK/8`, and `"8"` is in `CLKDIV`'s own
documented set, `prim_sim.v:12944`).  Every producer and consumer of the
primitive is a package ball (`D105`): the parallel word comes off two balls,
even bits from one and odd bits from the other, and the serialised output
drives a third, so the design holds no fabric cell whose free placement would
give a scoped net two identities.

If the vendor **accepts**, this row is the adjudication only -- an `E1`
placement-identical shape and the two open-flow implementations are a
follow-up task, not something absorbed here (`P3.T16`'s Done-when says so).
"""
from ._io_base import GEARBOX_CLKDIV_INS_LOC, IoShape

#: One point: the primitive either exists on this die or it does not.
POINTS = {"oser16-default": 16}

BASELINE = "oser16-default"

OSER_BALL = "AA9"          # IOB53A, cell (108,52), sk9822_da
DIN_EVEN_BALL = "W15"      # IOB72A, sd_cs
DIN_ODD_BALL = "W16"       # IOB72B, LCD_CTP[0], pair of W15
RESET_BALL = "T16"         # IOB76A, LCD_CTP[2]
RESETN_BALL = "AB13"       # IOB89B, Key_in[0], the CLKDIV's own reset
FCLK_BALL = "V22"          # IOB104B, the board oscillator

#: The serialiser's own pad cell -- the only cell an IOLOGIC is realised in.
SCOPE_TILES = ((52, 108),)

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

#: A 16-bit gearbox divides its `FCLK` by eight.  The divider is written here
#: rather than taken from `_io_base.clkdiv_rtl`, whose `GEARBOX_DIV_MODE`
#: table is keyed by the widths `io_ser` and `io_des` sweep and asserts it
#: covers exactly those: a width the vendor may not have is not a member of
#: that table until this row says it is.
DIV_MODE = "8"


def _clkdiv_rtl():
    return (
        '    CLKDIV pclk_div (\n'
        '        .HCLKIN (fclk),\n'
        '        .RESETN (resetn),\n'
        '        .CALIB  (1\'b0),\n'
        '        .CLKOUT (pclk)\n'
        '    );\n'
        '    defparam pclk_div.DIV_MODE = "%s";\n' % DIV_MODE)


_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_ser16.py -- do not edit.
// Shape: io_ser16 (primitive under test: OSER16)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din_even,
    input  wire din_odd,
    output wire dout
);

    wire pclk;

{clkdiv}
    OSER16 dut (
{ports}    );

endmodule

`default_nettype wire
"""


def _port_block(width):
    lines = ["        .%-6s (din_%s)," % ("D%d" % i,
                                          "even" if i % 2 == 0 else "odd")
             for i in range(width - 1, -1, -1)]
    lines += [
        "        .FCLK   (fclk),",
        "        .PCLK   (pclk),",
        "        .RESET  (rst),",
        "        .Q      (dout)",
    ]
    return "\n".join(lines) + "\n"


class IoSer16Shape(IoShape):
    """One `OSER16` on a bank-5 ball of HCLK block 4."""

    name = "io_ser16"
    primitive = "OSER16"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "fclk": (FCLK_BALL, "input"),
        "resetn": (RESETN_BALL, "input", {"pull_mode": "UP"}),
        "rst": (RESET_BALL, "input", {"pull_mode": "DOWN"}),
        "din_even": (DIN_EVEN_BALL, "input"),
        "din_odd": (DIN_ODD_BALL, "input"),
        "dout": (OSER_BALL, "output"),
    }
    clocks = {"fclk": 8.0}
    config_role_acks = {FCLK_BALL: _ACK_CLK}
    scope_tiles = SCOPE_TILES
    ins_loc = {"pclk_div": GEARBOX_CLKDIV_INS_LOC}

    def rtl(self, sweep_value):
        width = POINTS[sweep_value]
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            clkdiv=_clkdiv_rtl(), ports=_port_block(width))


SPEC = IoSer16Shape().spec()
