"""`iodelay_a_iddr` -- the delayed path with a clocked endpoint and no fabric.

`P3.T23`-`T25` measured the sharp fact: at `C_STATIC_DLY = 0` the vendor
programs the `IODELAY` fuse set and the open flow reproduces it (`E1`, `ok`),
but at `C_STATIC_DLY = 128` on `iodelay_a_balls` -- a pad-to-pad path with no
clock -- the vendor programs no `IOLOGIC` fuse while keeping the primitive.
`iodelay_a_clocked` then confirmed the rule by adding a fabric flop: at the
same 128 the vendor programs the step exactly.  **A static delay is programmed
only when the delayed net reaches a clocked endpoint.**

That row had to stay `E0`, and not because the rule is uncertain: the capture
flop is a *fabric* cell, GowinSynthesis renames it, so `INS_LOC` cannot pin it
in both flows and the scoped net has two identities (`D105`).  The eight
`conns` it differed by were the flop's, and nothing else.

This shape keeps the endpoint and drops the fabric.  The delayed output is
captured by an `IDDR` -- the register that already lives in the same `IOLOGIC`
as the delay line -- and both its outputs leave on package balls.  Every
producer and consumer in the design is a ball or the pad cell under test, so
the design holds no freely placed cell at all and the row can close at `E1`
without weakening what it asserts.

One point, `C_STATIC_DLY = 128`: the value that produced no fuse without an
endpoint and the vendor's full step with one.
"""
from ._io_base import IoShape
from .iodelay_a import POINTS
from .iodelay_a_balls import DLYSTEP_BALLS

#: The one point: the value the context rule was measured on.
IDDR_POINTS = ("c-static-dly-128",)

BASELINE = IDDR_POINTS[0]

DIN_BALL = "AA9"           # IOB53A, cell (108,52) -- the delayed pad
SDTAP_BALL = "AB13"        # IOB89B, Key_in[0]
VALUE_BALL = "Y13"         # IOB87A, cmos_sda
CLK_BALL = "V22"           # IOB104B, the board oscillator
Q0_BALL = "P20"            # IOB92A, LCD_BL
Q1_BALL = "W20"            # IOB122B, RGMII_RST_N
DF_BALL = "T16"            # IOB76A, LCD_CTP[2]

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/iodelay_a_iddr.py -- do not edit.
// Shape: iodelay_a_iddr (primitive under test: IODELAY)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire din,
    input  wire clk,
    input  wire sdtap,
    input  wire value,
{step_ports}
    output wire q0,
    output wire q1,
    output wire df
);

    wire [7:0] dlystep = {{{step_concat}}};
    wire delayed;

    IODELAY dut (
        .DI      (din),
        .SDTAP   (sdtap),
        .VALUE   (value),
        .DLYSTEP (dlystep),
        .DF      (df),
        .DO      (delayed)
    );
{defparams}
    // The endpoint, and the whole difference from `iodelay_a_clocked`: the
    // capturing register is the one inside this pad's own IOLOGIC, so the
    // design holds no fabric cell whose free placement would give the scoped
    // net a second identity.
    IDDR cap (
        .D   (delayed),
        .CLK (clk),
        .Q0  (q0),
        .Q1  (q1)
    );

endmodule

`default_nettype wire
"""


class IodelayIddrShape(IoShape):
    """One `IODELAY` whose delayed output is captured by the pad's own IDDR."""

    name = "iodelay_a_iddr"
    primitive = "IODELAY"
    sweep_axis = "C_STATIC_DLY"
    sweep_values = list(IDDR_POINTS)
    baseline_value = BASELINE
    ports = dict(
        [("din", (DIN_BALL, "input")),
         ("clk", (CLK_BALL, "input")),
         ("sdtap", (SDTAP_BALL, "input", {"pull_mode": "UP"})),
         ("value", (VALUE_BALL, "input")),
         ("q0", (Q0_BALL, "output")),
         ("q1", (Q1_BALL, "output")),
         ("df", (DF_BALL, "output"))]
        + [("step%d" % i, (ball, "input"))
           for i, ball in enumerate(DLYSTEP_BALLS)]
    )
    clocks = {"clk": 8.0}
    config_role_acks = {CLK_BALL: _ACK_CLK}
    scope_tiles = ((52, 108),)

    def rtl(self, sweep_value):
        parameter, value = POINTS[sweep_value]
        step_ports = "\n".join("    input  wire step%d," % i
                               for i in range(len(DLYSTEP_BALLS)))
        step_concat = ", ".join("step%d" % i
                                for i in reversed(range(len(DLYSTEP_BALLS))))
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            step_ports=step_ports, step_concat=step_concat,
            defparams="    defparam dut.%s = %s;\n" % (parameter, value))


SPEC = IodelayIddrShape().spec()
