"""`iodelay_a_clocked` -- the delayed path with a real timing endpoint.

`P3.T23`-`T25` measured something sharp and unexplained: at
`C_STATIC_DLY = 0` the vendor programs the `IODELAY` fuse set and the open
flow reproduces it (`E1`, `ok`), but at `C_STATIC_DLY = 128` **the vendor
programs no `IOLOGIC` fuse at all while keeping the primitive in the
netlist**. The static delay is therefore *context dependent*: something about
the design decides whether the vendor honours the parameter, and
`iodelay_a_balls` -- whose delayed output goes straight to a pad and whose
step bus comes off pads -- does not have it (`D107`, `D108`).

The hypothesis this shape tests, and the only one the earlier rows leave
standing: **a static delay is a timing quantity, and the vendor programs it
only when the delayed signal reaches a timing endpoint.** In
`iodelay_a_balls` the delayed net runs pad-to-pad, a path with no clock and
no register, so a static delay on it changes nothing any analysis can see. So
here the delayed output is captured by a fabric flop clocked by the board
oscillator, with a `create_clock` on it (the harness writes one from
`clocks`), which is the smallest change that gives the path an endpoint.

One run, at `C_STATIC_DLY = 128` -- the value that produced no fuse. The
verdict is read off the vendor's own bitstream: if the `IOLOGIC` fuse is now
programmed, the context rule is "a static delay needs a timing endpoint" and
the row goes to `E1` on a follow-up; if it is still absent, the rule is
something else and the measurement says so rather than leaving the earlier
`E0` unexplained.

This shape is deliberately **not** `D105`-clean: the capture flop is the
point. It cannot reach `E1` on `conns` (`P3.T12` measured that
GowinSynthesis renames a fabric flop, so `INS_LOC` cannot pin it), and it does
not try to -- what it measures is the *vendor's* fuse, which needs no open
half at all.
"""
from ._io_base import IoShape
from .iodelay_a import POINTS
from .iodelay_a_balls import DLYSTEP_BALLS

#: The one point: the value at which the vendor programmed nothing.
CLOCKED_POINTS = ("c-static-dly-128",)

BASELINE = CLOCKED_POINTS[0]

DIN_BALL = "AA9"           # IOB53A, cell (108,52) -- the delayed pad
SDTAP_BALL = "AB13"        # IOB89B, Key_in[0]
VALUE_BALL = "Y13"         # IOB87A, cmos_sda
CLK_BALL = "V22"           # IOB104B, the board oscillator
DOUT_BALL = "P20"          # IOB92A, LCD_BL
DF_BALL = "T16"            # IOB76A, LCD_CTP[2]

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/iodelay_a_clocked.py -- do not edit.
// Shape: iodelay_a_clocked (primitive under test: IODELAY)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire din,
    input  wire clk,
    input  wire sdtap,
    input  wire value,
{step_ports}
    output wire dout,
    output wire df
);

    wire [7:0] dlystep = {{{step_concat}}};
    wire delayed;

    IODELAY dut (
        .DI      (din),
        .SDTAP   (sdtap),
        .VALUE   (value),
        .DLYSTEP (dlystep),
        .DF      (df),
        .DO      (delayed)
    );
{defparams}
    // The whole point of this shape: the delayed net ends at a register, so
    // the path it is on has a timing endpoint the static delay can move.
    reg captured;
    always @(posedge clk) captured <= delayed;
    assign dout = captured;

endmodule

`default_nettype wire
"""


class IodelayClockedShape(IoShape):
    """One `IODELAY` whose delayed output is captured by a fabric flop."""

    name = "iodelay_a_clocked"
    primitive = "IODELAY"
    sweep_axis = "C_STATIC_DLY"
    sweep_values = list(CLOCKED_POINTS)
    baseline_value = BASELINE
    ports = dict(
        [("din", (DIN_BALL, "input")),
         ("clk", (CLK_BALL, "input")),
         ("sdtap", (SDTAP_BALL, "input", {"pull_mode": "UP"})),
         ("value", (VALUE_BALL, "input")),
         ("dout", (DOUT_BALL, "output")),
         ("df", (DF_BALL, "output"))]
        + [("step%d" % i, (ball, "input"))
           for i, ball in enumerate(DLYSTEP_BALLS)]
    )
    clocks = {"clk": 8.0}
    config_role_acks = {CLK_BALL: _ACK_CLK}
    scope_tiles = ((52, 108),)

    def rtl(self, sweep_value):
        parameter, value = POINTS[sweep_value]
        step_ports = "\n".join("    input  wire step%d," % i
                               for i in range(len(DLYSTEP_BALLS)))
        step_concat = ", ".join("step%d" % i
                                for i in reversed(range(len(DLYSTEP_BALLS))))
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            step_ports=step_ports, step_concat=step_concat,
            defparams="    defparam dut.%s = %s;\n" % (parameter, value))


SPEC = IodelayClockedShape().spec()
