"""`iodelay_a_balls` -- shape A with every net inside the scope (`P3.T22`).

`iodelay_a` closed `E0` with `cells` 0 and `attrs` 0 but `conns` 8: its
`DLYSTEP` bus came off a fabric counter, and a counter is placed freely by
each flow, so eight of the delay cell's port nets carried two different
endpoint digests for a reason that has nothing to do with `IODELAY`.  `D105`
is the rule that closes it -- *a shape whose context cells the vendor renames
must keep every net inside the scope* -- and this is that rule applied: the
eight step bits come off package balls, the delayed output goes straight to a
ball, and the design holds **no fabric cell at all**, so there is nothing left
for either placer to disagree about.

Everything else is `iodelay_a`: the same ball for the delayed input, the same
scope tile, the same `C_STATIC_DLY` semantics.  Only the context is gone.
"""
from ._io_base import IoShape
from .iodelay_a import POINTS

#: The two points the re-shape re-runs.  The sweep itself is `iodelay_a`'s and
#: is already attributed (`P3.F2`: `attrs` 0 on every built point); what is
#: open is the `conns` residual, and a residual that is 8 on every point is
#: settled by two points -- one at the documented default and one with the
#: top step bit set, the bit `P3.T20` once refused for want of an attr id.
RESHAPE_POINTS = ("c-static-dly-0", "c-static-dly-128")

BASELINE = RESHAPE_POINTS[0]

#: The eight balls the `DLYSTEP` bus is driven from, LSB first.  All bank 5,
#: all in `_io_base.SAFE_PINS`, none with a config role.
DLYSTEP_BALLS = ("W14", "Y14", "Y16", "AA16", "AB16", "AB17", "AA15", "W15")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/iodelay_a_balls.py -- do not edit.
// Shape: iodelay_a_balls (primitive under test: IODELAY)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire din,
    input  wire sdtap,
    input  wire value,
{step_ports}
    output wire dout,
    output wire df
);

    // Every net of the cell under test ends on a package ball (`D105`): no
    // flop, no counter, no LUT -- nothing either flow places by choice.
    wire [7:0] dlystep = {{{step_concat}}};

    IODELAY dut (
        .DI      (din),
        .SDTAP   (sdtap),
        .VALUE   (value),
        .DLYSTEP (dlystep),
        .DF      (df),
        .DO      (dout)
    );
{defparams}
endmodule

`default_nettype wire
"""


class IodelayBallsShape(IoShape):
    """One `IODELAY` whose every port net ends on a ball."""

    name = "iodelay_a_balls"
    primitive = "IODELAY"
    sweep_axis = "POINT"
    sweep_values = list(RESHAPE_POINTS)
    baseline_value = BASELINE
    ports = dict(
        [("din", ("AA9", "input")),
         ("sdtap", ("AB13", "input", {"pull_mode": "UP"})),
         ("value", ("Y13", "input")),
         ("dout", ("P20", "output")),
         ("df", ("Y17", "output"))]
        + [("step%d" % i, (ball, "input"))
           for i, ball in enumerate(DLYSTEP_BALLS)]
    )
    #: `AA9` is `IOB53A` at column 52, row 108 -- see `iodelay_a` for why the
    #: delayed ball cannot be `N15`.
    scope_tiles = ((52, 108),)

    def rtl(self, sweep_value):
        parameter, value = POINTS[sweep_value]
        step_ports = "\n".join("    input  wire step%d," % i
                               for i in range(len(DLYSTEP_BALLS)))
        step_concat = ", ".join("step%d" % i
                                for i in reversed(range(len(DLYSTEP_BALLS))))
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            step_ports=step_ports, step_concat=step_concat,
            defparams="    defparam dut.%s = %s;\n" % (parameter, value))


SPEC = IodelayBallsShape().spec()
