"""`iodelay_a` -- shape **A** of `spec-harness.md` §7 on the 138C (`P3.T21`).

One `IODELAY` on an input ball feeding a fabric flop, on a 3.3 V non-DDR
bank, sweeping `C_STATIC_DLY` across its 0-255 range plus the two boolean
parameters.  The GW5A port set is `IODELAY(DI, SDTAP, VALUE, DLYSTEP[7:0],
DF, DO)` with `C_STATIC_DLY`, `DYN_DLY_EN` and `ADAPT_EN`
(`cells_xtra_gw5a.v:1090`) -- **no `SETN`**, which is the GW1N/GW2A port and
the difference `D23` is about.

`C_STATIC_DLY` is swept **Gray-coded**: 24 of the 256 values, chosen so
adjacent runs differ in exactly one bit.  That is what makes a moved fuse
attributable to a single delay bit rather than to a whole new value, and it
is why the sweep is 24 points and not 256: every one of the eight bits is
toggled at least once, the low five at least twice, so a bit whose fuse moves
inconsistently shows up as a disagreement between its own sightings rather
than needing a second sweep.

An `IODELAY` is attributes on the IOLOGIC bel, not a bel of its own
(`chipdb.py:4204-4235`), so the shape's `E0` scope is the IO cell.
"""
from ._io_base import IoShape

#: The 24 `C_STATIC_DLY` points: a walk through the Gray code starting from
#: the documented default `0`, toggling every one of the eight bits at least
#: once (bits 0-2 four times, 3-4 three, 5-6 twice, 7 once).  Adjacent entries
#: differ in exactly one bit, which the shape's test re-derives rather than
#: trusting this list.
C_STATIC_DLY_POINTS = [
    0, 1, 3, 2, 6, 4, 12, 8, 24, 16, 48, 32, 96, 64, 192, 128,
    129, 131, 130, 134, 132, 140, 136, 152,
]

#: `(parameter, value)` per sweep point.  One axis per run (`F12`).
POINTS = dict(
    [("c-static-dly-%d" % value, ("C_STATIC_DLY", str(value)))
     for value in C_STATIC_DLY_POINTS]
    + [("dyn-dly-en-true", ("DYN_DLY_EN", '"TRUE"')),
       ("dyn-dly-en-false", ("DYN_DLY_EN", '"FALSE"')),
       ("adapt-en-true", ("ADAPT_EN", '"TRUE"')),
       ("adapt-en-false", ("ADAPT_EN", '"FALSE"'))]
)

#: The documented default (`cells_xtra_gw5a.v:1091`), so the baseline is the
#: same design at the default rather than an empty design.
BASELINE = "c-static-dly-0"

_ACK_CLK = ("EMCCLK: 27 vendor runs on this device placed a design with clk "
            "on V22 and gw_sh returned 0 every time (P1.T08d, "
            "$OTC/evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K "
            "board clock and examples/gw5a/tangmega138k.cst names it")

_TEMPLATE = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/iodelay_a.py -- do not edit.
// Shape: iodelay_a (primitive under test: IODELAY)
// Sweep: {axis} = {point}
`default_nettype none

module {top} (
    input  wire clk,
    input  wire din,
    input  wire sdtap,
    input  wire value,
    output wire dout,
    output wire df
);

    wire delayed;
    reg  captured;
    // Declared before use: `default_nettype none` makes an implicit net an
    // error, and the DLYSTEP bus is read by the instance above its counter.
    reg [7:0] dlystep;

    IODELAY dut (
        .DI      (din),
        .SDTAP   (sdtap),
        .VALUE   (value),
        .DLYSTEP (dlystep),
        .DF      (df),
        .DO      (delayed)
    );
{defparams}
    // The dynamic step port is driven from a fabric counter rather than tied
    // off: a constant DLYSTEP lets the synthesiser fold the bus away, and the
    // packer then emits no dynamic-delay fuses to compare.
    always @(posedge clk)
        dlystep <= dlystep + 8'd1;

    always @(posedge clk)
        captured <= delayed;

    assign dout = captured;

endmodule

`default_nettype wire
"""


class IodelayShape(IoShape):
    """One `IODELAY` on a bank-4 input ball, on a 3.3 V bank."""

    name = "iodelay_a"
    primitive = "IODELAY"
    sweep_axis = "POINT"
    sweep_values = list(POINTS)
    baseline_value = BASELINE
    ports = {
        "clk": ("V22", "input"),
        "din": ("N15", "input"),
        "sdtap": ("AB13", "input", {"pull_mode": "UP"}),
        "value": ("Y13", "input"),
        "dout": ("P20", "output"),
        "df": ("Y17", "output"),
    }
    clocks = {"clk": 20.0}
    config_role_acks = {"V22": _ACK_CLK}

    def rtl(self, sweep_value):
        parameter, value = POINTS[sweep_value]
        return _TEMPLATE.format(
            axis=self.sweep_axis, point=sweep_value, top=self.top_module,
            defparams="    defparam dut.%s = %s;\n" % (parameter, value))


def gray_adjacent_bit_changes():
    """Bit-count of every adjacent transition in `C_STATIC_DLY_POINTS`.

    Exposed so the property the sweep rests on is checked rather than
    asserted in a comment.
    """
    return [bin(a ^ b).count("1")
            for a, b in zip(C_STATIC_DLY_POINTS, C_STATIC_DLY_POINTS[1:])]


SPEC = IodelayShape().spec()
