"""`smoke` -- the one shape Phase 0 ships (`P0.T20`).

A 4-stage shift register whose **primitive under test is a single `DFF`**.
The `DFF` instance is pinned by an `INS_LOC "top.dut_dff" R2C3[0][A];` line so
its tile is deterministic, and `scope=ScopeSpec(tiles=[(2, 1)])` names exactly
that one tile: R2C3 is row 2, column 3, i.e. 0-based `(x, y) = (2, 1)`.

The remaining three stages are **context, not compared** (F6).  GowinSynthesis
and yosys do not emit the same LUT4/DFF decomposition, so a whole-design E0
comparison of this shape would be either meaningless or unreachable; the scope
restriction is what makes `diff=0` a real verdict.

Pins are in banks 4 and 5 -- never 6 or 7 (`D20c`, `D54`) -- at package
locations taken from `examples/gw5a/tangmega138k.cst` and cross-checked
against the chipdb `pin_bank` table for `GW5AST-LV138PG484AC1/I0`:

    clk   V22  IOB104B  bank 4
    rst_n Y12  IOB60B   bank 5
    din   V14  IOB66B   bank 5
    dout  P19  IOB99A   bank 4

`smoke` is a **single-point** shape: it has no swept parameter (`sweep_axis`
is `"none"`, one sweep value), because its job is to prove the flow end to end,
not to attribute a fuse.  Every real sweep is a later phase's row.
"""
from . import PinSpec, ScopeSpec, ShapeSpec

RTL = """\
// Generated by fuzz.gw5ast138c.harness.gen from shapes/smoke.py -- do not edit.
// Shape: {name} (primitive under test: {primitive})
// Sweep: {sweep_axis} = {sweep_value}
`default_nettype none

module {top_module} (
    input  wire clk,
    input  wire rst_n,
    input  wire din,
    output wire dout
);

    // The primitive under test: one DFF, pinned by INS_LOC so its tile is
    // deterministic and the E0 scope is exactly that tile.
    wire dut_q;
    DFF dut_dff (
        .D   (din),
        .CLK (clk),
        .Q   (dut_q)
    );

    // Context stages -- NOT compared (see the module docstring, F6).
    reg [2:0] ctx;
    always @(posedge clk) begin
        if (!rst_n)
            ctx <= 3'b000;
        else
            ctx <= {{ctx[1:0], dut_q}};
    end

    assign dout = ctx[2];

endmodule

`default_nettype wire
"""


def rtl(spec, sweep_value=None):
    """Render this shape's Verilog for one sweep point."""
    return RTL.format(
        name=spec.name,
        primitive=spec.primitive,
        sweep_axis=spec.sweep_axis,
        sweep_value=sweep_value,
        top_module=spec.top_module,
    )


SPEC = ShapeSpec(
    name="smoke",
    primitive="DFF",
    sweep_axis="none",
    sweep_values=[None],
    baseline_value=None,
    pins={
        "clk": PinSpec(loc="V22", bank=4),
        "rst_n": PinSpec(loc="Y12", bank=5, pull_mode="UP"),
        "din": PinSpec(loc="V14", bank=5, pull_mode="UP"),
        "dout": PinSpec(loc="P19", bank=4),
    },
    bank_vccio={4: "3.3", 5: "3.3"},
    scope=ScopeSpec(tiles=[(2, 1)]),
    rtl=rtl,
    ins_loc={"top.dut_dff": "R2C3[0][A]"},
    clocks={"clk": 20.0},
)
