"""Every `AE350_SOC` tap points the way the vendor's own routing points it.

The block sits in die row 0, a row of tiles that carry pips but no bels, so a
tap is an ordinary local wire and its direction is that wire's role in the
routing graph. The chipdb decides that role from the wire's class; this file
holds the decision against a source the class rule did not produce -- the pips
the vendor set in the banked bitstream of the 149-port vehicle, decoded per
row-0 tile into `tests/data/ae350-pip-roles-138c.json` (regenerated by
`open-toolchain/tools/derive_ae350_pip_roles.py`, which needs the 34 MB `.fs`;
the fixture is committed so the test does not).

A wire the vendor ends a pip on is driven by the fabric, so the block reads it:
an input. A wire the vendor starts a pip from has no driver in a bel-less tile
other than the block: an output. Nothing in row 0 is both, and a flipped
direction therefore shows up as a tap on the wrong side of that split.
"""

import json
import re
from pathlib import Path

import pytest

from apycula import chipdb as chipdb_mod

DEVICE = "GW5AST-138C"
ANCHOR = (0, 159)

#: Wire classes a fabric tap can name. A port bound to anything else is not on
#: the fabric, and the routing graph says nothing about it.
TAP_WIRE = re.compile(r"(?:A|B|C|D|F|Q|OF|CE|CLK|LSR)\d+\Z")

#: The classes the vendor is seen to drive into, and the classes it only reads
#: from. Asserted against the fixture before they are used to read the map.
FABRIC_DRIVEN_CLASSES = frozenset({"A", "B", "C", "D", "CE", "CLK", "LSR"})
BLOCK_DRIVEN_CLASSES = frozenset({"F", "Q", "OF"})

FIXTURE = Path(__file__).resolve().parent / "data" / "ae350-pip-roles-138c.json"


def wire_class(wire):
    return re.match(r"[A-Z]+", wire).group()


@pytest.fixture(scope="module")
def portmap():
    """`(ins, outs, block)` with every port resolved to its `(row, col, wire)`."""
    path = Path(__file__).resolve().parent.parent / "apycula" / f"{DEVICE}.msgpack.xz"
    if not path.is_file():
        pytest.skip(f"{path} is absent; run `make apycula/{DEVICE}.msgpack.xz`")
    db = chipdb_mod.load_chipdb(str(path))
    block = db.extra_func[ANCHOR]["ae350"]

    def resolve(value):
        if value.startswith(chipdb_mod._AE350_UNMAPPED_PREFIX):
            return None
        node = db.nodes.get(f"X{ANCHOR[1]}Y{ANCHOR[0]}/{value}")
        if node is None:
            return (ANCHOR[0], ANCHOR[1], value)
        elsewhere = [loc for loc in node[1] if loc[2] != value]
        assert len(elsewhere) == 1, (value, node)
        return tuple(elsewhere[0])

    return ({p: resolve(v) for p, v in block["ins"].items()},
            {p: resolve(v) for p, v in block["outs"].items()},
            block)


@pytest.fixture(scope="module")
def pip_roles():
    """`{(row, col): (destination wires, source wires)}` from the vendor run."""
    payload = json.loads(FIXTURE.read_text())
    roles = {}
    for key, entry in payload["tiles"].items():
        row, col = (int(part) for part in key.split(","))
        roles[(row, col)] = (set(entry.get("ae350_dest", ())),
                             set(entry.get("ae350_src", ())))
    return roles


def test_row0_wire_classes_are_one_way_in_the_vendor_routing(pip_roles):
    """No row-0 class is both driven into and read from by the vendor.

    This is the premise the map rests on, and it is what makes a direction
    sound for the few bits this vehicle never exercises.
    """
    seen = {}
    for dest, src in pip_roles.values():
        for wire in dest:
            seen.setdefault(wire_class(wire), set()).add("destination")
        for wire in src:
            seen.setdefault(wire_class(wire), set()).add("source")
    both = {cls: roles for cls, roles in seen.items() if len(roles) > 1}
    assert both == {}
    assert {cls for cls, roles in seen.items() if roles == {"destination"}} >= \
        FABRIC_DRIVEN_CLASSES
    assert {cls for cls, roles in seen.items() if roles == {"source"}} >= \
        BLOCK_DRIVEN_CLASSES


def test_no_input_tap_sits_on_a_wire_the_vendor_reads(portmap, pip_roles):
    ins, _outs, _block = portmap
    wrong = {}
    decided = 0
    for port, tap in ins.items():
        if tap is None or not TAP_WIRE.fullmatch(tap[2]):
            continue
        dest, src = pip_roles.get((tap[0], tap[1]), (set(), set()))
        if tap[2] in src:
            wrong[port] = tap
        elif tap[2] in dest:
            decided += 1
    assert wrong == {}
    assert decided == 415


def test_no_output_tap_sits_on_a_wire_the_vendor_drives(portmap, pip_roles):
    _ins, outs, _block = portmap
    wrong = {}
    decided = 0
    for port, tap in outs.items():
        if tap is None or not TAP_WIRE.fullmatch(tap[2]):
            continue
        dest, src = pip_roles.get((tap[0], tap[1]), (set(), set()))
        if tap[2] in dest:
            wrong[port] = tap
        elif tap[2] in src:
            decided += 1
    assert wrong == {}
    assert decided == 453


def test_every_bound_port_is_a_fabric_tap_or_a_recorded_dedicated_edge(portmap):
    """A port off the fabric classes must be one the chipdb says is off it."""
    ins, outs, block = portmap
    dedicated = {(block.get("core_clk") or {}).get("wire")} - {None}
    off_fabric = {port: tap for half in (ins, outs)
                  for port, tap in half.items()
                  if tap is not None and not TAP_WIRE.fullmatch(tap[2])}
    assert {tap[2] for tap in off_fabric.values()} <= dedicated
