// Generated by fuzz.gw5ast138c.harness.gen from shapes/adc_osc.py -- do not edit.
// Shape: adc (primitive under test: ADCLRC)
// Sweep: POINT = adclrc-temp
`default_nettype none

module top (
    input  wire clk,
    input  wire drstn,
    input  wire adcen,
    input  wire adcreq,
    output wire rdy,
    output wire fold,
    output wire q0,
    output wire q1,
    output wire q2,
    output wire q3,
    output wire q4,
    output wire q5,
    output wire q6,
    output wire q7,
    output wire q8,
    output wire q9
);

    wire [13:0] adcvalue;

    ADCLRC dut (
        .VSENCTL      (3'd1),
        .FSCAL_VALUE  (10'd730),
        .OFFSET_VALUE (-12'sd1180),
        .ADCEN        (adcen),
        .CLK          (clk),
        .DRSTN        (drstn),
        .ADCREQI      (adcreq),
        .ADCRDY       (rdy),
        .ADCVALUE     (adcvalue)
    );

    assign {q9, q8, q7, q6, q5, q4, q3, q2, q1, q0} = adcvalue[9:0];
    // Bank 5 brings out eleven free balls, not fifteen: the high four bits
    // are reduced onto one.  See the module docstring.
    assign fold = ^adcvalue[13:10];

endmodule

`default_nettype wire
