// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_basic.py -- do not edit.
// Shape: io_basic (primitive under test: IDDR)
// Sweep: POINT = iddr-default
`default_nettype none

module top (
    input  wire clk,
    input  wire din,
    input  wire d1,
    output wire dout,
    output wire dout2,
    output wire dout3
);

    IDDR dut (
        .D   (din),
        .CLK (clk),
        .Q0  (dout),
        .Q1  (dout2)
    );
    assign dout3 = d1;

endmodule

`default_nettype wire
