// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_des.py -- do not edit.
// Shape: io_des (primitive under test: IDES4)
// Sweep: POINT = ides4-reset-pad
`default_nettype none

module top (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din,
    output wire tap,
    output wire q0,
    output wire q1,
    output wire q2,
    output wire q3,
    output wire q4,
    output wire q5,
    output wire q6,
    output wire q7,
    output wire q8,
    output wire q9
);

    wire pclk;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "2";

    IDES4 dut (
        .Q3     (q3),
        .Q2     (q2),
        .Q1     (q1),
        .Q0     (q0),
        .FCLK   (fclk),
        .PCLK   (pclk),
        .RESET  (rst),
        .CALIB  (1'b0),
        .D      (din)
    );

    assign tap = rst;
    // The bits this width does not deserialise still drive their own ball,
    // so no point leaves a top-level port undriven.
    assign q4 = rst;
    assign q5 = rst;
    assign q6 = rst;
    assign q7 = rst;
    assign q8 = rst;
    assign q9 = rst;

endmodule

`default_nettype wire
