// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_des16_balls.py -- do not edit.
// Shape: io_des16_balls (primitive under test: IDES16)
// Sweep: POINT = ides16-balls
`default_nettype none

module top (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din,
    output wire q0,
    output wire q1,
    output wire q2,
    output wire q3,
    output wire q4,
    output wire q5,
    output wire q6,
    output wire q7,
    output wire q8,
    output wire q9
);

    wire pclk;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "8";

    IDES16 dut (
        .Q9     (q9),
        .Q8     (q8),
        .Q7     (q7),
        .Q6     (q6),
        .Q5     (q5),
        .Q4     (q4),
        .Q3     (q3),
        .Q2     (q2),
        .Q1     (q1),
        .Q0     (q0),
        .FCLK   (fclk),
        .PCLK   (pclk),
        .RESET  (rst),
        .CALIB  (1'b0),
        .D      (din)
    );

endmodule

`default_nettype wire
