// Generated by fuzz.gw5ast138c.harness.gen from shapes/iodelay_a_iddr.py -- do not edit.
// Shape: iodelay_a_iddr (primitive under test: IODELAY)
// Sweep: C_STATIC_DLY = c-static-dly-128
`default_nettype none

module top (
    input  wire din,
    input  wire clk,
    input  wire sdtap,
    input  wire value,
    input  wire step0,
    input  wire step1,
    input  wire step2,
    input  wire step3,
    input  wire step4,
    input  wire step5,
    input  wire step6,
    input  wire step7,
    output wire q0,
    output wire q1,
    output wire df
);

    wire [7:0] dlystep = {step7, step6, step5, step4, step3, step2, step1, step0};
    wire delayed;

    IODELAY dut (
        .DI      (din),
        .SDTAP   (sdtap),
        .VALUE   (value),
        .DLYSTEP (dlystep),
        .DF      (df),
        .DO      (delayed)
    );
    defparam dut.C_STATIC_DLY = 128;

    // The endpoint, and the whole difference from `iodelay_a_clocked`: the
    // capturing register is the one inside this pad's own IOLOGIC, so the
    // design holds no fabric cell whose free placement would give the scoped
    // net a second identity.
    IDDR cap (
        .D   (delayed),
        .CLK (clk),
        .Q0  (q0),
        .Q1  (q1)
    );

endmodule

`default_nettype wire
