// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_basic.py -- do not edit.
// Shape: io_basic (primitive under test: ODDR)
// Sweep: POINT = oddr-default
`default_nettype none

module top (
    input  wire clk,
    input  wire din,
    input  wire d1,
    output wire dout,
    output wire dout2,
    output wire dout3
);

    ODDR dut (
        .D0  (din),
        .D1  (d1),
        .TX  (1'b0),
        .CLK (clk),
        .Q0  (dout),
        .Q1  ()
    );
    // Both serialiser inputs come off pads and Q0 drives one, so every net of
    // the scoped tile has both its endpoints at an `IO_LOC`-pinned site.
    assign dout2 = d1;
    assign dout3 = din;

endmodule

`default_nettype wire
