// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_ser16.py -- do not edit.
// Shape: io_ser16 (primitive under test: OSER16)
// Sweep: POINT = oser16-default
`default_nettype none

module top (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din_even,
    input  wire din_odd,
    output wire dout
);

    wire pclk;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "8";

    OSER16 dut (
        .D15    (din_odd),
        .D14    (din_even),
        .D13    (din_odd),
        .D12    (din_even),
        .D11    (din_odd),
        .D10    (din_even),
        .D9     (din_odd),
        .D8     (din_even),
        .D7     (din_odd),
        .D6     (din_even),
        .D5     (din_odd),
        .D4     (din_even),
        .D3     (din_odd),
        .D2     (din_even),
        .D1     (din_odd),
        .D0     (din_even),
        .FCLK   (fclk),
        .PCLK   (pclk),
        .RESET  (rst),
        .Q      (dout)
    );

endmodule

`default_nettype wire
