// Generated by fuzz.gw5ast138c.harness.gen from shapes/io_ser.py -- do not edit.
// Shape: io_ser (primitive under test: OSER8)
// Sweep: POINT = oser8-default
`default_nettype none

module top (
    input  wire fclk,
    input  wire resetn,
    input  wire rst,
    input  wire din_even,
    input  wire din_odd,
    output wire dout
);

    wire pclk;

    CLKDIV pclk_div (
        .HCLKIN (fclk),
        .RESETN (resetn),
        .CALIB  (1'b0),
        .CLKOUT (pclk)
    );
    defparam pclk_div.DIV_MODE = "4";

    OSER8 dut (
        .D7     (din_odd),
        .D6     (din_even),
        .D5     (din_odd),
        .D4     (din_even),
        .D3     (din_odd),
        .D2     (din_even),
        .D1     (din_odd),
        .D0     (din_even),
        .TX3    (1'b1),
        .TX2    (1'b1),
        .TX1    (1'b1),
        .TX0    (1'b1),
        .FCLK   (fclk),
        .PCLK   (pclk),
        .RESET  (rst),
        .Q0     (dout),
        .Q1     ()
    );

endmodule

`default_nettype wire
