// Generated by fuzz.gw5ast138c.harness.gen from shapes/diff_io.py -- do not edit.
// Shape: diff_io_iobuf (primitive under test: TLVDS_IOBUF)
// Sweep: POINT = tlvds-iobuf
`default_nettype none

module top (
    input  wire din,
    input  wire oen,
    output wire dout,
    inout  wire pad_p,
    inout  wire pad_n
);

    wire rx;

    // Every net stays inside the IO tiles: the buffer's `I`/`OEN` come
    // straight off package balls and `dout` is driven by the buffer's `O`
    // where it has one, by `din` where it has not.  A context flop here
    // would be a fabric cell neither flow is constrained to place
    // identically -- the `P3.T12` residue `D105` closed by rule.
    assign dout = rx;

    TLVDS_IOBUF dut (
        .O   (rx),
        .IO  (pad_p),
        .IOB (pad_n),
        .I   (din),
        .OEN (oen)
    );

endmodule

`default_nettype wire
