// Generated by fuzz.gw5ast138c.harness.gen from shapes/diff_io.py -- do not edit.
// Shape: diff_io (primitive under test: TLVDS_TBUF)
// Sweep: POINT = tlvds-tbuf
`default_nettype none

module top (
    input  wire din,
    input  wire oen,
    output wire dout,
    output wire pad_p,
    output wire pad_n
);

    wire rx;

    // Every net stays inside the IO tiles: the buffer's `I`/`OEN` come
    // straight off package balls and `dout` is driven by the buffer's `O`
    // where it has one, by `din` where it has not.  A context flop here
    // would be a fabric cell neither flow is constrained to place
    // identically -- the `P3.T12` residue `D105` closed by rule.
    assign dout = din;

    TLVDS_TBUF dut (
        .I   (din),
        .OEN (oen),
        .O   (pad_p),
        .OB  (pad_n)
    );

endmodule

`default_nettype wire
